import { useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, Cable, RefreshCw, Watch } from "lucide-react";

const providers = [
  { id: "apple_health", name: "Apple Health", note: "Exige integração nativa iOS; não disponível no navegador." },
  { id: "google_health", name: "Google Health", note: "Conexão web disponível após configurar credenciais Google." },
  { id: "health_connect", name: "Health Connect", note: "Exige integração nativa Android e permissões do sistema." },
  { id: "garmin", name: "Garmin", note: "Exige credenciais e acesso aprovados pelo programa Garmin." },
  { id: "coros", name: "COROS", note: "Conexão individual pelo OAuth e MCP oficial." },
] as const;
type ProviderId = (typeof providers)[number]["id"];

export default function SmartwatchPage() {
  const { user, loading } = useAuth();
  const today = trpc.progress.today.useQuery(undefined, { enabled: Boolean(user) });
  const connections = trpc.progress.wearableConnections.useQuery(undefined, { enabled: Boolean(user) });
  const weekly = trpc.progress.weeklyActivityAnalysis.useQuery({ from: today.data?.weekStart ?? "2000-01-01", to: today.data?.weekEnd ?? "2000-01-07", weekStart: today.data?.weekStart ?? "2000-01-01" }, { enabled: Boolean(user && today.data) });
  const [selected, setSelected] = useState<ProviderId>("coros");
  const [notice, setNotice] = useState("");
  const request = trpc.progress.requestWearableConnection.useMutation({ onSuccess: result => { if (result.authorizationUrl) window.location.assign(result.authorizationUrl); else setNotice(result.message); void connections.refetch(); }, onError: error => setNotice(error.message) });
  const sync = trpc.progress.requestWearableSync.useMutation({ onSuccess: result => { setNotice(result.message); void Promise.all([connections.refetch(), weekly.refetch()]); }, onError: error => setNotice(error.message) });
  const summary = weekly.data;
  if (loading) return <main className="grid min-h-screen place-items-center">Carregando…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-3xl border bg-white p-8 text-center"><h1 className="text-2xl font-semibold">Entre para conectar um dispositivo</h1><Link href="/login" className="mt-4 inline-flex rounded-xl bg-emerald-950 px-4 py-3 font-semibold text-white">Entrar</Link></div></main>;
  return <main className="min-h-screen bg-[#f6f8f6] px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>Painel</Link><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">Dados autorizados</p><h1 className="mt-1 text-3xl font-semibold">Smartwatch e saúde</h1><p className="mt-2 max-w-2xl text-slate-600">Conecte a fonte que você usa. Métricas só aparecem após autorização e sincronização reais; o aplicativo não preenche dados ausentes.</p>
    <section className="mt-7 grid gap-4 md:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-3"><Watch className="text-emerald-900"/><h2 className="font-semibold">Conexões</h2></div><div className="mt-4 space-y-3">{providers.map(provider => { const connection = connections.data?.find(item => item.provider === provider.id); return <article key={provider.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{provider.name}</h3><p className="mt-1 text-sm text-slate-500">{provider.note}</p><small className="mt-2 block text-slate-500">{connection?.status === "connected" ? connection.lastSyncStatus === "synced" ? "Conectado e sincronizado" : "Conectado, aguardando sincronização" : connection?.status === "disconnected" ? "Desconectado" : "Autorização necessária"}</small>{connection?.lastSyncError && <small className="mt-1 block text-amber-800">{connection.lastSyncError}</small>}</div><div className="flex gap-2"><button disabled={request.isPending} onClick={() => { setSelected(provider.id); request.mutate({ provider: provider.id }); }} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold"><Cable size={14}/>Conectar</button>{connection?.status === "connected" && <button disabled={sync.isPending} onClick={() => { setSelected(provider.id); if (today.data) sync.mutate({ provider: provider.id, from: today.data.weekStart, to: today.data.activityDate }); }} className="rounded-lg bg-emerald-950 px-3 py-2 text-sm font-semibold text-white">{sync.isPending && selected === provider.id ? "Sincronizando…" : "Sincronizar"}</button>}</div></div></article>; })}</div>{notice && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900" role="status">{notice}</p>}</div>
      <aside className="space-y-4"><section className="rounded-3xl bg-emerald-950 p-6 text-white"><div className="flex items-center gap-3"><Activity/><h2 className="font-semibold">Resumo desta semana</h2></div><div className="mt-5 grid grid-cols-2 gap-3">{[{ label: "Atividades", value: summary?.activityCount }, { label: "Cardio", value: summary?.cardioMinutes == null ? null : summary.cardioMinutes + " min" }, { label: "Calorias de treino", value: summary?.workoutCaloriesKcal == null ? null : summary.workoutCaloriesKcal + " kcal" }, { label: "Frequência cardíaca média", value: summary?.averageHeartRate == null ? null : summary.averageHeartRate + " bpm" }, { label: "Sono", value: summary?.sleepMinutes == null ? null : summary.sleepMinutes + " min" }, { label: "Passos", value: summary?.steps }].map(item => <div key={item.label} className="rounded-xl bg-white/10 p-3"><small className="text-emerald-200">{item.label}</small><strong className="mt-1 block">{item.value ?? "Sem dado disponível"}</strong></div>)}</div><p className="mt-4 text-xs text-emerald-200">{summary?.sources?.length ? "Fontes: " + summary.sources.join(", ") : "Nenhuma fonte sincronizada nesta semana."}</p></section><section className="rounded-3xl border bg-white p-6"><h2 className="font-semibold">Privacidade e disponibilidade</h2><p className="mt-2 text-sm leading-6 text-slate-600">Tokens ficam cifrados no servidor e os dados são isolados por conta. Apple Health e Health Connect precisam de um bridge móvel nativo; Garmin depende de aprovação externa. Quando a conexão não está disponível, o estado é informado sem dados simulados.</p><button className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-900" onClick={() => void Promise.all([connections.refetch(), weekly.refetch()])}><RefreshCw size={14}/>Atualizar estado</button></section></aside></section>
  </div></main>;
}
