import { wearableState, wearableStateLabels } from "@shared/wearable-status";
import { useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, Cable, RefreshCw, Watch } from "lucide-react";

const providers = [
  { id: "apple_health", name: "Apple Health", note: "Exige integração nativa iOS; não disponível no navegador." },
  { id: "google_health", name: "Google Health", note: "Conexão web disponível após configurar credenciais Google." },
  { id: "health_connect", name: "Health Connect", note: "Exige integração nativa Android e permissões do sistema." },
  { id: "garmin", name: "Garmin", note: "Exige credenciais e acesso aprovados pelo programa Garmin." },
  { id: "coros", name: "COROS", note: "Conexão individual pelo OAuth e MCP oficial." },
] as const;
type ProviderId = (typeof providers)[number]["id"];
type Language = "pt" | "en" | "es";

const copy = {
  pt: { loading:"Carregando…", signTitle:"Entre para conectar um dispositivo", signIn:"Entrar", panel:"Painel", authorized:"Dados autorizados", title:"Smartwatch e saúde", intro:"Conecte a fonte que você usa. Métricas só aparecem após autorização e sincronização reais; o aplicativo não preenche dados ausentes.", error:"Não foi possível carregar os dados de smartwatch.", connections:"Conexões", connect:"Conectar", syncing:"Sincronizando…", sync:"Sincronizar", disconnect:"Desconectar", week:"Resumo desta semana", activities:"Atividades", cardio:"Cardio", calories:"Calorias de treino", heart:"Frequência cardíaca média", sleep:"Sono", steps:"Passos", noData:"Sem dado disponível", sources:"Fontes", noSources:"Nenhuma fonte sincronizada nesta semana.", privacyTitle:"Privacidade e disponibilidade", privacy:"Tokens ficam cifrados no servidor e os dados são isolados por conta. Apple Health e Health Connect precisam de um bridge móvel nativo; Garmin depende de aprovação externa. Quando a conexão não está disponível, o estado é informado sem dados simulados.", refresh:"Atualizar estado" },
  en: { loading:"Loading…", signTitle:"Sign in to connect a device", signIn:"Sign in", panel:"Dashboard", authorized:"Authorized data", title:"Smartwatch and health", intro:"Connect the source you use. Metrics only appear after real authorization and synchronization; the app does not fill in missing data.", error:"Smartwatch data could not be loaded.", connections:"Connections", connect:"Connect", syncing:"Syncing…", sync:"Sync", disconnect:"Disconnect", week:"This week's summary", activities:"Activities", cardio:"Cardio", calories:"Workout calories", heart:"Average heart rate", sleep:"Sleep", steps:"Steps", noData:"No data available", sources:"Sources", noSources:"No sources synchronized this week.", privacyTitle:"Privacy and availability", privacy:"Tokens are encrypted on the server and data is isolated by account. Apple Health and Health Connect require a native mobile bridge; Garmin depends on external approval. When a connection is unavailable, its state is reported without simulated data.", refresh:"Refresh status" },
  es: { loading:"Cargando…", signTitle:"Inicia sesión para conectar un dispositivo", signIn:"Iniciar sesión", panel:"Panel", authorized:"Datos autorizados", title:"Smartwatch y salud", intro:"Conecta la fuente que utilizas. Las métricas solo aparecen después de una autorización y sincronización reales; la aplicación no completa datos ausentes.", error:"No se pudieron cargar los datos del smartwatch.", connections:"Conexiones", connect:"Conectar", syncing:"Sincronizando…", sync:"Sincronizar", disconnect:"Desconectar", week:"Resumen de esta semana", activities:"Actividades", cardio:"Cardio", calories:"Calorías de entrenamiento", heart:"Frecuencia cardíaca media", sleep:"Sueño", steps:"Pasos", noData:"Sin datos disponibles", sources:"Fuentes", noSources:"Ninguna fuente sincronizada esta semana.", privacyTitle:"Privacidad y disponibilidad", privacy:"Los tokens se cifran en el servidor y los datos se aíslan por cuenta. Apple Health y Health Connect requieren un puente móvil nativo; Garmin depende de aprobación externa. Cuando una conexión no está disponible, se informa su estado sin datos simulados.", refresh:"Actualizar estado" },
} as const;

const providerNotes: Record<Language, Record<ProviderId, string>> = {
  pt: Object.fromEntries(providers.map(p => [p.id, p.note])) as Record<ProviderId,string>,
  en: { apple_health:"Requires native iOS integration; unavailable in the browser.", google_health:"Web connection available after Google credentials are configured.", health_connect:"Requires native Android integration and system permissions.", garmin:"Requires credentials and approved Garmin program access.", coros:"Individual connection through OAuth and the official MCP." },
  es: { apple_health:"Requiere integración nativa de iOS; no disponible en el navegador.", google_health:"Conexión web disponible tras configurar las credenciales de Google.", health_connect:"Requiere integración nativa de Android y permisos del sistema.", garmin:"Requiere credenciales y acceso aprobado al programa Garmin.", coros:"Conexión individual mediante OAuth y el MCP oficial." },
};

export default function SmartwatchPage() {
  const { user, loading } = useAuth();
  const language = ((localStorage.getItem("ritmo-language") || localStorage.getItem("ritmo-mf-language") || "pt") as Language);
  const c = copy[language] ?? copy.pt;
  const today = trpc.progress.today.useQuery(undefined, { enabled: Boolean(user) });
  const connections = trpc.progress.wearableConnections.useQuery(undefined, { enabled: Boolean(user) });
  const weekly = trpc.progress.weeklyActivityAnalysis.useQuery({ from: today.data?.weekStart ?? "2000-01-01", to: today.data?.weekEnd ?? "2000-01-07", weekStart: today.data?.weekStart ?? "2000-01-01" }, { enabled: Boolean(user && today.data) });
  const [selected, setSelected] = useState<ProviderId>("coros");
  const [notice, setNotice] = useState("");
  const request = trpc.progress.requestWearableConnection.useMutation({ onSuccess: result => { if (result.authorizationUrl) window.location.assign(result.authorizationUrl); else setNotice(result.message); void connections.refetch(); }, onError: error => setNotice(error.message) });
  const sync = trpc.progress.requestWearableSync.useMutation({ onSuccess: result => { setNotice(result.message); void Promise.all([connections.refetch(), weekly.refetch()]); }, onError: error => setNotice(error.message) });
  const disconnect = trpc.progress.disconnectWearable.useMutation({onSuccess:()=>{void connections.refetch();void weekly.refetch();},onError:error=>setNotice(error.message)});
  const summary = weekly.data;
  if (loading) return <main className="grid min-h-screen place-items-center">{c.loading}</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-3xl border bg-white p-8 text-center text-slate-950"><h1 className="text-2xl font-semibold">{c.signTitle}</h1><Link href="/login" className="mt-4 inline-flex rounded-xl bg-emerald-950 px-4 py-3 font-semibold !text-white">{c.signIn}</Link></div></main>;
  return <main className="min-h-screen bg-[#0b0d0c] workout-workspace px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>{c.panel}</Link><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">{c.authorized}</p><h1 className="mt-1 text-3xl font-semibold">{c.title}</h1><p className="mt-2 max-w-2xl text-slate-600">{c.intro}</p>
    {(connections.error || weekly.error) && <p role="alert">{c.error}</p>}<section className="mt-7 grid gap-4 md:grid-cols-[1.1fr_.9fr]"><div className="rounded-3xl border bg-white p-6"><div className="flex items-center gap-3"><Watch className="text-emerald-900"/><h2 className="font-semibold">{c.connections}</h2></div><div className="mt-4 space-y-3">{providers.map(provider => { const connection = connections.data?.find(item => item.provider === provider.id); return <article key={provider.id} className="rounded-2xl border p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{provider.name}</h3><p className="mt-1 text-sm text-slate-500">{providerNotes[language][provider.id]}</p><small className="mt-2 block text-slate-500">{wearableStateLabels[language][wearableState(provider.id, connection, summary?.sources?.includes(provider.id))]}</small>{connection?.lastSyncError && <small className="mt-1 block text-amber-800">{connection.lastSyncError}</small>}</div><div className="flex gap-2"><button disabled={request.isPending || provider.id === "apple_health" || provider.id === "health_connect"} onClick={() => { setSelected(provider.id); request.mutate({ provider: provider.id }); }} className="inline-flex items-center gap-1 rounded-lg border px-3 py-2 text-sm font-semibold"><Cable size={14}/>{c.connect}</button>{connection?.status === "connected" && <button disabled={sync.isPending} onClick={() => { setSelected(provider.id); if (today.data) sync.mutate({ provider: provider.id, from: today.data.weekStart, to: today.data.activityDate }); }} className="rounded-lg bg-emerald-950 px-3 py-2 text-sm font-semibold text-white">{sync.isPending && selected === provider.id ? c.syncing : c.sync}</button>}{connection?.status === "connected" && <button disabled={disconnect.isPending} onClick={()=>disconnect.mutate({provider:provider.id})} className="rounded-lg border px-3 py-2 text-sm font-semibold">{c.disconnect}</button>}</div></div></article>; })}</div>{notice && <p className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900" role="status">{notice}</p>}</div>
      <aside className="space-y-4"><section className="rounded-3xl bg-emerald-950 p-6 text-white"><div className="flex items-center gap-3"><Activity/><h2 className="font-semibold">{c.week}</h2></div><div className="mt-5 grid grid-cols-2 gap-3">{[{ label: c.activities, value: summary?.activityCount }, { label: c.cardio, value: summary?.cardioMinutes == null ? null : summary.cardioMinutes + " min" }, { label: c.calories, value: summary?.workoutCaloriesKcal == null ? null : summary.workoutCaloriesKcal + " kcal" }, { label: c.heart, value: summary?.averageHeartRate == null ? null : summary.averageHeartRate + " bpm" }, { label: c.sleep, value: summary?.sleepMinutes == null ? null : summary.sleepMinutes + " min" }, { label: c.steps, value: summary?.steps }].map(item => <div key={item.label} className="rounded-xl bg-white/10 p-3"><small className="text-emerald-200">{item.label}</small><strong className="mt-1 block">{item.value ?? c.noData}</strong></div>)}</div><p className="mt-4 text-xs text-emerald-200">{summary?.sources?.length ? c.sources + ": " + summary.sources.join(", ") : c.noSources}</p></section><section className="rounded-3xl border bg-white p-6"><h2 className="font-semibold">{c.privacyTitle}</h2><p className="mt-2 text-sm leading-6 text-slate-600">{c.privacy}</p><button className="mt-4 inline-flex items-center gap-2 text-sm font-semibold text-emerald-900" onClick={() => void Promise.all([connections.refetch(), weekly.refetch()])}><RefreshCw size={14}/>{c.refresh}</button></section></aside></section>
  </div></main>;
}
