import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CheckCircle2, CreditCard } from "lucide-react";
import { useRitmoLanguage } from "@/lib/ritmo-language";

export default function SubscriptionPage() {
  const { user, loading } = useAuth();
  const [language] = useRitmoLanguage();
  const tx = {
    pt:{loading:"Carregando…",loginTitle:"Entre para ver sua assinatura",login:"Entrar",home:"Início",kicker:"Plano e pagamentos",title:"Assinatura Ritmo Pro",active:"ATIVA",month:"mês",billing:"Cobrança recorrente em BRL processada pelo Mercado Pago.",until:"Acesso válido até",last:"Último pagamento",opening:"Abrindo checkout…",subscribe:"Assinar por",continue:"Continuar pagamento",canceling:"Cancelando…",cancel:"Cancelar assinatura",confirm:"Deseja cancelar sua assinatura?",foot:"Plano mensal. Cancelamento e cobrança seguem as condições apresentadas no checkout do Mercado Pago."},
    en:{loading:"Loading…",loginTitle:"Sign in to view your subscription",login:"Sign in",home:"Home",kicker:"Plan and payments",title:"Ritmo Pro Subscription",active:"ACTIVE",month:"month",billing:"Recurring BRL billing processed by Mercado Pago.",until:"Access valid until",last:"Last payment",opening:"Opening checkout…",subscribe:"Subscribe for",continue:"Continue payment",canceling:"Cancelling…",cancel:"Cancel subscription",confirm:"Do you want to cancel your subscription?",foot:"Monthly plan. Cancellation and billing follow the conditions shown in Mercado Pago checkout."},
    es:{loading:"Cargando…",loginTitle:"Entra para ver tu suscripción",login:"Entrar",home:"Inicio",kicker:"Plan y pagos",title:"Suscripción Ritmo Pro",active:"ACTIVA",month:"mes",billing:"Cobro recurrente en BRL procesado por Mercado Pago.",until:"Acceso válido hasta",last:"Último pago",opening:"Abriendo checkout…",subscribe:"Suscribirse por",continue:"Continuar pago",canceling:"Cancelando…",cancel:"Cancelar suscripción",confirm:"¿Quieres cancelar tu suscripción?",foot:"Plan mensual. La cancelación y el cobro siguen las condiciones mostradas en el checkout de Mercado Pago."}
  }[language];
  const query = trpc.profile.subscription.useQuery(undefined, { enabled: Boolean(user) });
  const utils = trpc.useUtils();
  const checkout = trpc.profile.checkout.useMutation({ onSuccess: result => { if (result.checkoutUrl) window.location.assign(result.checkoutUrl); else void query.refetch(); } });
  const cancel = trpc.profile.cancelSubscription.useMutation({ onSuccess: () => utils.profile.subscription.invalidate() });
  if (loading) return <main className="grid min-h-screen place-items-center">{tx.loading}</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-3xl border bg-white p-8 text-center"><h1 className="text-2xl font-semibold">{tx.loginTitle}</h1><Link href="/login" className="mt-4 inline-flex rounded-xl bg-emerald-950 px-4 py-3 font-semibold text-white">{tx.login}</Link></div></main>;
  const info = query.data; const offer = info?.offer;
  const price = offer ? new Intl.NumberFormat(language === "en" ? "en-US" : language === "es" ? "es-ES" : "pt-BR", { style: "currency", currency: offer.currency }).format(Number(offer.amount)) : "R$ 33,99";
  const status = info?.status ?? tx.loading;
  const canSubscribe = !info || ["none", "cancelled", "expired", "error"].includes(info.status);
  const canCancel = Boolean(info && ["pending", "active", "payment_pending"].includes(info.status));
  return <main className="subscription-page min-h-screen px-4 py-8 sm:px-8"><div className="mx-auto max-w-3xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>{tx.home}</Link><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">{tx.kicker}</p><h1 className="mt-1 text-3xl font-semibold">{tx.title}</h1><section className="subscription-surface mt-7 rounded-3xl border p-7 shadow-sm sm:p-9"><div className="flex items-start justify-between gap-4"><div><span className="inline-flex items-center gap-2 rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-900"><CheckCircle2 size={14}/>{info?.premium ? tx.active : String(status).toUpperCase()}</span><h2 className="mt-4 text-2xl font-semibold">{price}<span className="text-base font-normal text-slate-500"> / {tx.month}</span></h2><p className="mt-2 text-sm text-slate-600">{tx.billing}</p></div><CreditCard className="text-emerald-900"/></div>{info?.currentPeriodEnd && <p className="mt-5 text-sm text-slate-600">{tx.until} {new Date(info.currentPeriodEnd).toLocaleDateString(language === "en" ? "en-US" : language === "es" ? "es-ES" : "pt-BR")}</p>}{info?.lastPaymentStatus && <p className="mt-1 text-sm text-slate-600">{tx.last}: {info.lastPaymentStatus}</p>}<div className="mt-6 flex flex-wrap gap-3">{canSubscribe && <button disabled={checkout.isPending || query.isLoading} onClick={() => checkout.mutate()} className="rounded-xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{checkout.isPending ? tx.opening : tx.subscribe + " " + price + "/" + tx.month}</button>}{info && ["pending", "payment_pending"].includes(info.status) && <button disabled={checkout.isPending} onClick={() => checkout.mutate()} className="rounded-xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white">{tx.continue}</button>}{canCancel && <button disabled={cancel.isPending} onClick={() => { if (window.confirm(tx.confirm)) cancel.mutate(); }} className="rounded-xl border border-red-200 px-5 py-3 text-sm font-semibold text-red-700">{cancel.isPending ? tx.canceling : tx.cancel}</button>}</div>{(checkout.error || cancel.error) && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-800">{checkout.error?.message || cancel.error?.message}</p>}<p className="mt-7 text-xs text-slate-500">{tx.foot}</p></section></div></main>;
}
