import { useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { ArrowLeft, CalendarCheck } from "lucide-react";

const options = {
  objectiveMan: [["vshape", "Shape em V"], ["strength", "Força"], ["fatloss", "Redução de gordura"], ["performance", "Performance e condicionamento"]],
  objectiveWoman: [["performance_curves", "Melhor performance + glúteos e pernas em destaque"], ["glute_focus", "Glúteos em destaque"], ["legs_glutes", "Pernas e glúteos mais desenvolvidos"], ["lower_body", "Maior desenvolvimento de membros inferiores"], ["balanced_feminine", "Shape feminino equilibrado e atlético"], ["conditioning", "Performance e condicionamento"], ["fatloss_definition", "Redução de gordura + definição"], ["strength_lower", "Força com foco em inferiores"]],
  cardio: [["none", "Não faço cardio"], ["u20", "Até 20 minutos"], ["20_30", "20–30 minutos"], ["30_45", "30–45 minutos"], ["45_60", "45–60 minutos"], ["over60", "Mais de 60 minutos"]],
  sleep: [["under7", "Menos de 7 horas"], ["7_8", "7–8 horas"], ["8_9", "8–9 horas"], ["9_10", "9–10 horas"], ["over10", "Mais de 10 horas"]],
  recovery: [["very_low", "Muito baixa"], ["low", "Baixa"], ["normal", "Normal"], ["good", "Boa"], ["very_good", "Muito boa"]],
  fatigue: [["fresh", "Recuperado"], ["some", "Alguma fadiga"], ["moderate", "Moderada"], ["high", "Alta"], ["very_high", "Muito alta"]],
  bench: [["b1", "Até 8 kg por lado"], ["b2", "8–12 kg por lado"], ["b3", "12–17,5 kg por lado"], ["b4", "17,5–22,5 kg por lado"], ["b5", "22,5–27,5 kg por lado"], ["b6", "27,5–32,5 kg por lado"], ["b7", "32,5–37,5 kg por lado"], ["b8", "37,5–42,5 kg por lado"], ["b9", "42,5–47,5 kg por lado"], ["b10", "47,5–52,5 kg por lado"], ["b11", "52,5–57,5 kg por lado"], ["b12", "57,5–60 kg por lado"], ["b13", "Mais de 60 kg por lado"]],
  squat: [["s1", "Até 10 kg por lado"], ["s2", "10–20 kg por lado"], ["s3", "20–30 kg por lado"], ["s4", "30–40 kg por lado"], ["s5", "40–50 kg por lado"], ["s6", "50–60 kg por lado"], ["s7", "60–70 kg por lado"], ["s8", "70–80 kg por lado"], ["s9", "80–90 kg por lado"], ["s10", "90–100 kg por lado"], ["s11", "100–110 kg por lado"], ["s12", "110–120 kg por lado"], ["s13", "Mais de 120 kg por lado"]],
} as const;
type Assessment = { objective: string; heightCm: string; benchPressLevel: string; squatLevel: string; cardio: string; sleep: string; recovery: string; fatigue: string };
const empty: Assessment = { objective: "", heightCm: "", benchPressLevel: "", squatLevel: "", cardio: "", sleep: "", recovery: "", fatigue: "" };

export default function WeeklyAssessmentPage() {
  const { user, loading } = useAuth(); const utils = trpc.useUtils();
  const today = trpc.progress.today.useQuery(undefined, { enabled: Boolean(user) });
  const weekStart = today.data?.weekStart ?? "2000-01-01";
  const current = trpc.progress.currentAssessment.useQuery({ weekStart }, { enabled: Boolean(user && today.data) });
  const history = trpc.progress.assessmentHistory.useQuery(undefined, { enabled: Boolean(user) });
  const [draft, setDraft] = useState<Assessment>(empty); const [notice, setNotice] = useState("");
  useEffect(() => { const row = current.data; if (row) setDraft({ objective: row.objective, heightCm: String(row.heightCm), benchPressLevel: row.benchPressLevel, squatLevel: row.squatLevel, cardio: row.cardio, sleep: row.sleep, recovery: row.recovery, fatigue: row.fatigue }); }, [current.data]);
  const save = trpc.progress.saveAssessment.useMutation({ onSuccess: async () => { setNotice("Avaliação semanal salva."); await Promise.all([utils.progress.currentAssessment.invalidate(), utils.progress.assessmentHistory.invalidate()]); }, onError: error => setNotice(error.message) });
  const filled = useMemo(() => Object.values(draft).filter(Boolean).length, [draft]);
  const objectiveOptions = user?.experience === "woman" ? options.objectiveWoman : options.objectiveMan;
  const field = (key: keyof Assessment, label: string, entries?: ReadonlyArray<readonly [string, string]>) => <label key={key} className="text-sm font-medium">{label}{entries ? <select required value={draft[key]} onChange={e => setDraft({ ...draft, [key]: e.target.value })} className="mt-1.5 w-full rounded-xl border bg-white px-3 py-2.5"><option value="">Selecione</option>{entries.map(([value, text]) => <option key={value} value={value}>{text}</option>)}</select> : <input required min={100} max={250} type="number" value={draft.heightCm} onChange={e => setDraft({ ...draft, heightCm: e.target.value })} className="mt-1.5 w-full rounded-xl border px-3 py-2.5" placeholder="cm"/>}</label>;
  if (loading) return <main className="grid min-h-screen place-items-center">Carregando…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-3xl border bg-white p-8 text-center"><h1 className="text-2xl font-semibold">Entre para salvar sua avaliação</h1><Link href="/login" className="mt-4 inline-flex rounded-xl bg-emerald-950 px-4 py-3 font-semibold text-white">Entrar</Link></div></main>;
  return <main className="assessment-page min-h-screen px-4 py-8 sm:px-8"><div className="mx-auto max-w-5xl"><Link href="/dashboard" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>Início</Link><p className="mt-6 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">Revisão semanal</p><h1 className="mt-1 text-3xl font-semibold">Sua avaliação da semana</h1><p className="mt-2 text-slate-600">Registre os dados atuais. O histórico anterior permanece salvo para comparar sua evolução.</p>
    <section className="mt-7 grid gap-5 lg:grid-cols-[1.3fr_.7fr]"><form onSubmit={event => { event.preventDefault(); save.mutate({ weekStart, objective: draft.objective, heightCm: Number(draft.heightCm), benchPressLevel: draft.benchPressLevel, squatLevel: draft.squatLevel, cardio: draft.cardio, sleep: draft.sleep, recovery: draft.recovery, fatigue: draft.fatigue }); }} className="assessment-surface rounded-3xl border p-6 shadow-sm sm:p-8"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">Semana iniciada em {weekStart}</h2><p className="mt-1 text-sm text-slate-500">{filled}/8 campos preenchidos</p></div><CalendarCheck className="text-emerald-900"/></div><div className="grid gap-4 sm:grid-cols-2">{field("objective", "Objetivo principal", objectiveOptions)}{field("heightCm", "Altura (cm)")}{field("benchPressLevel", "Supino por lado", options.bench)}{field("squatLevel", "Agachamento por lado", options.squat)}{field("cardio", "Cardio por sessão", options.cardio)}{field("sleep", "Sono habitual", options.sleep)}{field("recovery", "Recuperação", options.recovery)}{field("fatigue", "Fadiga após os quatro dias", options.fatigue)}</div>{notice && <p role="status" className="mt-4 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}<button disabled={save.isPending || filled < 8} className="mt-6 rounded-xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{save.isPending ? "Salvando…" : "Salvar avaliação"}</button></form>
      <aside className="assessment-surface rounded-3xl border p-6"><h2 className="font-semibold">Histórico de semanas</h2><p className="mt-1 text-sm text-slate-500">Cada semana é armazenada separadamente.</p>{history.data?.length ? <ol className="mt-4 space-y-3">{history.data.map(row => <li key={row.id} className="rounded-xl bg-slate-50 p-4"><strong>{row.weekStart}</strong><p className="mt-1 text-sm text-slate-600">{row.objective} · recuperação {row.recovery} · fadiga {row.fatigue}</p></li>)}</ol> : <p className="mt-5 text-sm text-slate-500">Ainda não há avaliações anteriores.</p>}<p className="mt-5 text-xs leading-5 text-slate-500">As recomendações são informativas e não substituem orientação profissional.</p></aside></section>
  </div></main>;
}
