import { useEffect, useMemo, useState } from "react";
import { Link, Redirect, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { useRitmoLanguage } from "@/lib/ritmo-language";
import { templatesFor, catalogFor, exerciseById, type ExerciseId } from "@shared/workouts";
import { originalSnapshot } from "@shared/fitness";
import { originalPrescriptions } from "@shared/original-prescriptions";
import { ArrowLeft, ArrowDown, ArrowUp, CheckCircle2, CircleAlert, Dumbbell, LoaderCircle, Plus, Send, Sparkles, Trash2 } from "lucide-react";


const ui:any={
 pt:{name:"Nome do treino",goal:"Objetivo",muscle:"Grupo muscular",duration:"Duração estimada (min)",notes:"Observações",exercises:"Exercícios",add:"Adicionar exercício",addMany:"Adicionar exercícios",selectGroup:"Selecione por grupo muscular.",close:"Fechar",search:"Pesquisar exercício…",already:"Já adicionado",selectExercises:"Selecione exercícios",empty:"Adicione o primeiro exercício para montar seu treino.",sets:"Séries",reps:"Repetições",load:"Carga (kg)",rest:"Descanso (seg.)",note:"Nota",loading:"Carregando sua conta…",signin:"Entrar",back:"Voltar ao treino",library:"Sua biblioteca",saved:"Treinos salvos",weekly:"Treinos por semana",suggested:"Quatro treinos sugeridos",plans:"Meus planos",run:"Executar",copy:"Copiar",edit:"Editar",remove:"Excluir treino",myworkouts:"Meus treinos",custom:"Treinamento personalizado",createAI:"Criar com IA",cancel:"Cancelar",saving:"Salvando…",save:"Salvar treino",saveChanges:"Salvar alterações"},
 en:{name:"Workout name",goal:"Goal",muscle:"Muscle group",duration:"Estimated duration (min)",notes:"Notes",exercises:"Exercises",add:"Add exercise",addMany:"Add exercises",selectGroup:"Select by muscle group.",close:"Close",search:"Search exercise…",already:"Already added",selectExercises:"Select exercises",empty:"Add the first exercise to build your workout.",sets:"Sets",reps:"Reps",load:"Load (kg)",rest:"Rest (sec.)",note:"Note",loading:"Loading your account…",signin:"Sign in",back:"Back to workout",library:"Your library",saved:"Saved workouts",weekly:"Workouts per week",suggested:"Four suggested workouts",plans:"My plans",run:"Start",copy:"Copy",edit:"Edit",remove:"Delete workout",myworkouts:"My workouts",custom:"Custom training",createAI:"Create with AI",cancel:"Cancel",saving:"Saving…",save:"Save workout",saveChanges:"Save changes"},
 es:{name:"Nombre del entrenamiento",goal:"Objetivo",muscle:"Grupo muscular",duration:"Duración estimada (min)",notes:"Observaciones",exercises:"Ejercicios",add:"Añadir ejercicio",addMany:"Añadir ejercicios",selectGroup:"Selecciona por grupo muscular.",close:"Cerrar",search:"Buscar ejercicio…",already:"Ya añadido",selectExercises:"Selecciona ejercicios",empty:"Añade el primer ejercicio para montar tu entrenamiento.",sets:"Series",reps:"Repeticiones",load:"Carga (kg)",rest:"Descanso (seg.)",note:"Nota",loading:"Cargando tu cuenta…",signin:"Entrar",back:"Volver al entrenamiento",library:"Tu biblioteca",saved:"Entrenamientos guardados",weekly:"Entrenamientos por semana",suggested:"Cuatro entrenamientos sugeridos",plans:"Mis planes",run:"Ejecutar",copy:"Copiar",edit:"Editar",remove:"Eliminar entrenamiento",myworkouts:"Mis entrenamientos",custom:"Entrenamiento personalizado",createAI:"Crear con IA",cancel:"Cancelar",saving:"Guardando…",save:"Guardar entrenamiento",saveChanges:"Guardar cambios"}
};
const W=(language:"pt"|"en"|"es",key:string)=>ui[language][key]??key;

type ExerciseDraft = { exerciseId: ExerciseId; sets: number; reps: string; loadKg: number | null; restSeconds: number; note: string | null };
type PlanDraft = { name: string; objective: string; focusGroup: string; durationMinutes: number; notes: string | null; exercises: ExerciseDraft[] };
const emptyPlan: PlanDraft = { name: "Meu treino", objective: "Hipertrofia", focusGroup: "Corpo todo", durationMinutes: 45, notes: "", exercises: [] };
const freshExercise = (exerciseId: ExerciseId): ExerciseDraft => ({ exerciseId, sets: 3, reps: "8–12", loadKg: null, restSeconds: 90, note: null });
const pickerGroup = (exercise: (typeof exerciseById)[ExerciseId]) => {
  const text = `${exercise.group} ${exercise.name}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase();
  if (/peito|chest|supino|crucifixo|fly/.test(text)) return "Peito";
  if (/costa|back|dorsal|remada|puxada|pulldown|row/.test(text)) return "Costas";
  if (/ombro|shoulder|deltoid|elevacao lateral|desenvolvimento/.test(text)) return "Ombros";
  if (/biceps|rosca/.test(text)) return "Bíceps";
  if (/triceps/.test(text)) return "Tríceps";
  if (/abd|core|prancha|crunch/.test(text)) return "Abdómen / Core";
  if (/panturr|calf|gemeos/.test(text)) return "Pernas · Panturrilhas";
  if (/glute|pelvic|hip thrust|abdutora|coice/.test(text)) return "Pernas · Glúteos";
  if (/posterior|hamstring|flexora|stiff|deadlift|romeno/.test(text)) return "Pernas · Posterior";
  return "Pernas · Quadríceps";
};
const pickerOrder = ["Peito", "Costas", "Ombros", "Bíceps", "Tríceps", "Abdómen / Core", "Pernas · Quadríceps", "Pernas · Posterior", "Pernas · Glúteos", "Pernas · Panturrilhas"];
const exerciseImage = (id: ExerciseId) => {
  const exercise = exerciseById[id] as (typeof exerciseById)[ExerciseId] & { image?: string };
  return exercise.image ?? originalPrescriptions[id]?.image ?? "";
};

function PlanFields({ value, onChange }: { value: PlanDraft; onChange: (next: PlanDraft) => void }) {
  const { user } = useAuth();
  const [language] = useRitmoLanguage();
  const catalogQuery = trpc.workouts.catalog.useQuery(undefined, { enabled: !!user });
  const exerciseCatalog = (catalogQuery.data ?? catalogFor(user?.experience ?? "man")) as ReturnType<typeof catalogFor>;
  const [pickerOpen, setPickerOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<ExerciseId[]>([]);
  const [activeGroup, setActiveGroup] = useState<string | null>(null);
  useEffect(() => { setSelected([]); setSearch(""); setActiveGroup(null); setPickerOpen(false); }, [user?.experience]);
  const update = (key: keyof PlanDraft, next: unknown) => onChange({ ...value, [key]: next });
  const updateExercise = (index: number, patch: Partial<ExerciseDraft>) => onChange({ ...value, exercises: value.exercises.map((item, i) => i === index ? { ...item, ...patch } : item) });
  const moveExercise = (index: number, by: number) => { const exercises = [...value.exercises]; const next = index + by; if (next < 0 || next >= exercises.length) return; [exercises[index], exercises[next]] = [exercises[next], exercises[index]]; onChange({ ...value, exercises }); };
  const groups = useMemo(() => pickerOrder.filter(group => exerciseCatalog.some(e => pickerGroup(e as (typeof exerciseById)[ExerciseId]) === group)), [exerciseCatalog]);
  const visibleGroups = search.trim() ? groups : activeGroup ? [activeGroup] : [];
  const addSelected = () => { const existing = new Set(value.exercises.map(e => e.exerciseId)); const additions = selected.filter(id => !existing.has(id)).map(freshExercise); onChange({ ...value, exercises: [...value.exercises, ...additions] }); setSelected([]); setSearch(""); setActiveGroup(null); setPickerOpen(false); };
  const toggle = (id: ExerciseId) => setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]);
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-medium">{W(language,"name")}<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" maxLength={120} value={value.name} onChange={e => update("name", e.target.value)} /></label>
      <label className="text-sm font-medium">{W(language,"goal")}<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" maxLength={80} value={value.objective} onChange={e => update("objective", e.target.value)} placeholder="Força, hipertrofia…" /></label>
      <label className="text-sm font-medium">{W(language,"muscle")}<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" maxLength={80} value={value.focusGroup} onChange={e => update("focusGroup", e.target.value)} /></label>
      <label className="text-sm font-medium">{W(language,"duration")}<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" type="number" min={10} max={240} value={value.durationMinutes} onChange={e => update("durationMinutes", Number(e.target.value))} /></label>
    </div>
    <label className="block text-sm font-medium">{W(language,"notes")}<textarea className="mt-1.5 w-full rounded-xl border px-3 py-2.5" rows={2} maxLength={2000} value={value.notes ?? ""} onChange={e => update("notes", e.target.value)} placeholder="Orientações para esta sessão" /></label>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">{W(language,"exercises")}</h3><p className="text-sm text-slate-500">Escolha por grupo muscular e adicione vários de uma vez.</p></div><button type="button" disabled={value.exercises.length >= 20} onClick={() => { setActiveGroup(null); setPickerOpen(true); }} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-50"><Plus size={16}/>{W(language,"add")}</button></div>
    {pickerOpen && <div className="rounded-2xl border bg-white p-4 shadow-lg"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">{W(language,"addMany")}</h3><p className="text-xs text-slate-500">{W(language,"selectGroup")}</p></div><button type="button" className="rounded-lg border px-3 py-2 text-sm" onClick={() => {setPickerOpen(false);setSelected([]);setSearch("");setActiveGroup(null);}}>{W(language,"close")}</button></div><input autoFocus className="mt-4 w-full rounded-xl border px-3 py-2.5" placeholder={W(language,"search")} value={search} onChange={e=>setSearch(e.target.value)}/>{!search.trim() && !activeGroup && <div className="mt-4 grid gap-2 sm:grid-cols-2">{groups.map(group => { const count=exerciseCatalog.filter(e=>pickerGroup(e as (typeof exerciseById)[ExerciseId])===group).length; return <button type="button" key={group} onClick={()=>setActiveGroup(group)} className="flex items-center justify-between rounded-xl border p-4 text-left hover:bg-slate-50"><span><strong className="block">{group}</strong><small className="text-slate-500">{count} exercício{count===1?'':'s'}</small></span><span aria-hidden="true">›</span></button>})}</div>}
{activeGroup && !search.trim() && <button type="button" onClick={()=>setActiveGroup(null)} className="mt-4 text-sm font-semibold">← Grupos musculares</button>}
<div className="mt-4 max-h-[55vh] space-y-4 overflow-y-auto pr-1">{visibleGroups.map(group => { const q=search.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase(); const items=exerciseCatalog.filter(e=>pickerGroup(e as (typeof exerciseById)[ExerciseId])===group && (!q || `${e.name} ${e.group}`.normalize("NFD").replace(/[\u0300-\u036f]/g, "").toLowerCase().includes(q))); if(!items.length)return null; return <section key={group}><h4 className="sticky top-0 z-10 bg-white py-2 text-sm font-bold uppercase tracking-wide">{group}</h4><div className="grid gap-2 sm:grid-cols-2">{items.map(exercise=>{const id=exercise.id as ExerciseId;const already=value.exercises.some(x=>x.exerciseId===id);const checked=selected.includes(id);const image=exerciseImage(id);return <button type="button" key={id} disabled={already} onClick={()=>toggle(id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${checked?'border-emerald-700 bg-emerald-50':''} disabled:opacity-60`}>{image && <img src={image} alt="" className="h-16 w-16 shrink-0 rounded-lg border bg-slate-100 object-cover" loading="lazy"/>}<span className="min-w-0 flex-1"><strong className="block text-sm">{exercise.name}</strong><small className="text-slate-500">{already?W(language,"already"):group}</small></span><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border font-bold">{already?'✓':checked?'✓':''}</span></button>})}</div></section>})}</div><button type="button" disabled={!selected.length || value.exercises.length + selected.length > 20} onClick={addSelected} className="mt-4 w-full rounded-xl bg-emerald-950 px-4 py-3 font-semibold text-white disabled:opacity-50">{selected.length ? `Adicionar ${selected.length} exercício${selected.length>1?'s':''}` : W(language,"selectExercises")}</button></div>}
    {!value.exercises.length && <div className="rounded-2xl border border-dashed p-7 text-center text-sm text-slate-500">{W(language,"empty")}</div>}
    <div className="space-y-3">{value.exercises.map((item,index)=><article key={`${index}-${item.exerciseId}`} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="mb-3 flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-emerald-950 text-xs font-bold text-white">{index+1}</span><strong className="min-w-0 flex-1 text-sm">{exerciseById[item.exerciseId].name} <span className="font-normal text-slate-500">· {exerciseById[item.exerciseId].group}</span></strong><button type="button" aria-label="Mover para cima" disabled={index===0} className="rounded-lg p-2 disabled:opacity-30" onClick={()=>moveExercise(index,-1)}><ArrowUp size={16}/></button><button type="button" aria-label="Mover para baixo" disabled={index===value.exercises.length-1} className="rounded-lg p-2 disabled:opacity-30" onClick={()=>moveExercise(index,1)}><ArrowDown size={16}/></button><button type="button" aria-label="Remover exercício" className="rounded-lg p-2 text-red-700" onClick={()=>onChange({...value,exercises:value.exercises.filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></div><div className="grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-slate-600">{W(language,"sets")}<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" type="number" min={1} max={10} value={item.sets} onChange={e=>updateExercise(index,{sets:Number(e.target.value)})}/></label><label className="text-xs font-semibold text-slate-600">{W(language,"reps")}<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" maxLength={24} value={item.reps} onChange={e=>updateExercise(index,{reps:e.target.value})}/></label></div></article>)}</div>
  </div>;
}
export function WorkoutsLibrary() {
  const { user, loading } = useAuth();
  const [language] = useRitmoLanguage(); const [, setLocation] = useLocation();
  const defaultWorkoutTemplates = templatesFor(user?.experience ?? "man");
  const query = trpc.workouts.list.useQuery(undefined, { enabled: !!user });
  const overview = trpc.fitness.overview.useQuery(undefined, { enabled: !!user });
  const utils = trpc.useUtils();
  const preferences = trpc.fitness.preferences.useMutation({ onSuccess: () => overview.refetch() });
  const copy = trpc.workouts.create.useMutation({ onSuccess: () => Promise.all([utils.workouts.list.invalidate(), utils.fitness.overview.invalidate()]) });
  const remove = trpc.workouts.remove.useMutation({ onSuccess: () => Promise.all([utils.workouts.list.invalidate(), utils.fitness.overview.invalidate()]) });
  if (loading) return <main className="grid min-h-screen place-items-center">{W(language,"loading")}</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="max-w-md rounded-3xl border bg-white p-8 text-center"><Dumbbell className="mx-auto text-emerald-900"/><h1 className="mt-4 text-2xl font-bold">Entre para ver seus treinos</h1><p className="my-3 text-slate-600">Seus planos ficam salvos com segurança na sua conta.</p><Link href="/login" className="inline-flex rounded-xl bg-emerald-950 px-5 py-3 font-semibold text-white">{W(language,"signin")}</Link></div></main>;
  if (user && !user.experience) return <Redirect to="/escolher-versao" />;
  return <main className="min-h-screen bg-[#0b0d0c] workout-workspace px-4 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/treino" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>{W(language,"back")}</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">{W(language,"library")}</p><h1 className="mt-1 text-3xl font-semibold">{W(language,"saved")}</h1><p className="mt-2 text-slate-600">Planos criados por você e personalizados a partir dos quatro treinos sugeridos.</p></div></header>
    <section className="mt-8"><div className="mb-5 rounded-2xl border bg-white p-5"><label className="text-sm font-semibold">{W(language,"weekly")}<select className="ml-3 rounded-lg border px-3 py-2" aria-label="Treinos por semana" value={overview.data?.preferences.workoutsPerWeek ?? 4} disabled={!overview.data || preferences.isPending} onChange={e => overview.data && preferences.mutate({ ...overview.data.preferences, workoutsPerWeek: Number(e.target.value) })}>{[1,2,3,4,5,6,7].map(n => <option key={n} value={n}>{n}</option>)}</select></label><p className="mt-2 text-sm text-slate-500">Escolha entre 1 e 7 treinos por semana. Os quatro treinos sugeridos permanecem como base.</p>{preferences.error && <p role="alert" className="mt-2 text-sm text-red-700">{preferences.error.message}</p>}</div><div className="mb-4"><h2 className="text-xl font-semibold">{W(language,"suggested")}</h2><p className="mt-1 text-sm text-slate-500">A estrutura original é mantida. Personalize criando uma cópia para sua conta.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(defaultWorkoutTemplates).map(([day, plan], index) => <article key={day} className="rounded-2xl border bg-white p-5"><span className="text-xs font-bold uppercase tracking-wider text-emerald-800">TREINO SUGERIDO {index + 1}</span><h3 className="mt-2 font-semibold">{plan.name}</h3><p className="mt-1 text-sm text-slate-500">{plan.focusGroup} · {plan.exercises.length} exercícios</p><Link href={"/treinos/criar?base=" + day} className="mt-4 inline-flex rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">Personalizar cópia</Link></article>)}<article className="rounded-2xl border bg-white p-5"><Sparkles className="text-emerald-800"/><h3 className="mt-2 font-semibold">Criar treino com IA</h3><Link href="/treinos/criar?mode=ai" className="mt-4 inline-flex rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">Criar treino com IA</Link></article></div></section>
    <div className="mb-4 mt-10"><h2 className="text-xl font-semibold">{W(language,"plans")}</h2><p className="mt-1 text-sm text-slate-500">Treinos privados criados e personalizados por você.</p></div>
    {(copy.error || remove.error) && <p role="alert">{copy.error?.message || remove.error?.message}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{query.isLoading && <p>Carregando seus treinos…</p>}{query.error && <p role="alert" className="text-red-700">Não foi possível carregar os treinos.</p>}{!query.isLoading && query.data?.length === 0 && <div className="rounded-2xl border border-dashed bg-white p-8 text-slate-600">Você ainda não salvou treinos. Crie um plano manual ou peça uma sugestão personalizada à IA.</div>}{query.data?.map(plan => <article key={plan.id} className="group rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-900">{plan.source === "ai" ? "CRIADO COM IA" : plan.source === "customized" ? "PERSONALIZADO" : plan.source === "day5" ? "DIA 5 OPCIONAL" : "MEU TREINO"}</span><h2 className="mt-3 text-lg font-semibold">{plan.name}</h2></div><Dumbbell className="shrink-0 text-emerald-900" size={20}/></div><p className="mt-1 text-sm text-slate-500">{plan.focusGroup} · {plan.durationMinutes} min</p><p className="mt-3 text-sm text-slate-700">{plan.exercises.length} exercícios · {plan.objective}</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/treino?plan=${plan.id}`} className="rounded-lg border px-3 py-2 text-sm font-semibold">{W(language,"run")}</Link><button disabled={copy.isPending} onClick={() => copy.mutate({name: (plan.name + " — cópia").slice(0,120),objective:plan.objective,focusGroup:plan.focusGroup,durationMinutes:plan.durationMinutes,notes:plan.notes,exercises:plan.exercises,source:"manual",baseWorkoutId:null})} className="rounded-lg border px-3 py-2 text-sm font-semibold">{W(language,"copy")}</button><button onClick={() => setLocation(`/treinos/criar?edit=${plan.id}`)} className="flex-1 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">{W(language,"edit")}</button><button disabled={remove.isPending} onClick={() => { if (window.confirm(`Excluir “${plan.name}”?`)) remove.mutate({ id: plan.id }); }} className="sm:opacity-0 group-hover:opacity-100 focus:opacity-100 rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">{W(language,"remove")}</button></div></article>)}</div>
  </div></main>;
}


function AIProgramBuilder({ user, language }: { user: NonNullable<ReturnType<typeof useAuth>["user"]>; language:"pt"|"en"|"es" }) {
  const [,setLocation]=useLocation(); const utils=trpc.useUtils();
  const context=trpc.workouts.aiContext.useQuery(); const [count,setCount]=useState(4); const [message,setMessage]=useState(""); const [goal,setGoal]=useState("");
  const [messages,setMessages]=useState<{role:"user"|"ai";text:string}[]>([]); const [plans,setPlans]=useState<PlanDraft[]>([]); const [error,setError]=useState(""); const fromAssessment=new URLSearchParams(window.location.search).get("from")==="assessment"; const [assessmentConfirmed,setAssessmentConfirmed]=useState(fromAssessment);
  const copy={pt:{title:"Criar com IA",lead:"O RITMO usa o contexto que você já forneceu para montar e refinar um programa completo em conversa.",context:"Contexto da IA",profile:"Perfil disponível",assessment:"Avaliação atual",body:"Análise corporal",photos:"Fotos corporais",complete:"Completar avaliação",full:"Criar treino com IA",fullDesc:"Escolha de 1 a 7 treinos e personalize em conversa.",howMany:"Quantos treinos você quer no seu plano?",prompt:"Conte uma prioridade ou preferência. A IA vai comparar seu pedido com seus dados.",placeholder:"Ex.: Quero priorizar costas e ombros, tenho cerca de 45 minutos...",start:"Montar programa",refine:"Enviar ajuste",save:"Salvar programa",saving:"Salvando…",missing:"Ainda não disponível",ready:"Disponível",draft:"Rascunho — a carga em kg é escolhida por você."},en:{title:"Create with AI",lead:"RITMO uses the context you already provided to build and refine a complete program through conversation.",context:"AI context",profile:"Profile available",assessment:"Current assessment",body:"Body analysis",photos:"Body photos",complete:"Complete assessment",full:"Create workout with AI",fullDesc:"Choose 1 to 7 workouts and personalize them in conversation.",howMany:"How many workouts do you want in your plan?",prompt:"Tell us a priority or preference. AI will compare it with your data.",placeholder:"E.g. I want to prioritize back and shoulders and have about 45 minutes...",start:"Build program",refine:"Send adjustment",save:"Save program",saving:"Saving…",missing:"Not available yet",ready:"Available",draft:"Draft — you choose the load in kg."},es:{title:"Crear con IA",lead:"RITMO usa el contexto que ya proporcionaste para crear y refinar un programa completo mediante conversación.",context:"Contexto de IA",profile:"Perfil disponible",assessment:"Evaluación actual",body:"Análisis corporal",photos:"Fotos corporales",complete:"Completar evaluación",full:"Crear entrenamiento con IA",fullDesc:"Elige de 1 a 7 entrenamientos y personalízalos conversando.",howMany:"¿Cuántos entrenamientos quieres en tu plan?",prompt:"Indica una prioridad o preferencia. La IA la comparará con tus datos.",placeholder:"Ej.: Quiero priorizar espalda y hombros y tengo unos 45 minutos...",start:"Crear programa",refine:"Enviar ajuste",save:"Guardar programa",saving:"Guardando…",missing:"Aún no disponible",ready:"Disponible",draft:"Borrador — tú eliges la carga en kg."}}[language];
  const generate=trpc.workouts.generateProgramWithAI.useMutation({onSuccess:r=>{setPlans(r.plans as PlanDraft[]);setMessages(v=>[...v,{role:"ai",text:r.reply}]);setMessage("");setError("");context.refetch()},onError:e=>setError(e.message)});
  const save=trpc.workouts.saveAIProgram.useMutation({onSuccess:async()=>{await utils.workouts.list.invalidate();setLocation("/treinos")},onError:e=>setError(e.message)});
  const send=()=>{if(!goal){setError(language==="pt"?"Selecione seu objetivo antes de montar o programa.":language==="es"?"Selecciona tu objetivo antes de crear el programa.":"Select your goal before building the program.");return} if(!assessmentConfirmed){setError(language==="pt"?"Confirme os dados da avaliação antes de gerar o treino.":language==="es"?"Confirma los datos de la evaluación antes de generar el entrenamiento.":"Confirm the assessment data before generating the workout.");return} const prefix=language==="pt"?"Objetivo principal":language==="es"?"Objetivo principal":"Primary goal"; const extra=message.trim()?`${language==="pt"?"Preferência adicional":language==="es"?"Preferencia adicional":"Additional preference"}: ${message.trim()}`:""; const text=`${prefix}: ${goal}.${extra?` ${extra}`:""}`;setMessages(v=>[...v,{role:"user",text}]);generate.mutate({trainingCount:count,userMessage:text,language,previousPlans:plans})};
  const status=(ok:boolean,label:string,detail?:string|number|null)=><div className="ai-context-row">{ok?<CheckCircle2 size={18}/>:<CircleAlert size={18}/>}<span><b>{label}</b><small>{ok?(detail?`${copy.ready} · ${detail}`:copy.ready):copy.missing}</small></span></div>;
  return <main className="min-h-screen workout-workspace px-4 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><Link href={fromAssessment?"/avaliacao":"/treinos"} className="inline-flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/>{fromAssessment?(language==="pt"?"Voltar à avaliação":language==="es"?"Volver a la evaluación":"Back to assessment"):W(language,"myworkouts")}</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.18em]">RITMO PRO · AI</p><h1 className="mt-1 text-3xl font-semibold">{copy.title}</h1><p className="mt-2 text-slate-500">{copy.lead}</p>
  <section className="ai-context-card"><div><h2>{copy.context}</h2><p>{language==="pt"?"Quanto mais completa estiver sua avaliação, maior será o contexto disponível para a IA.":language==="es"?"Cuanto más completa esté tu evaluación, mayor será el contexto disponible para la IA.":"The more complete your assessment is, the more context AI can use."}</p></div><div className="ai-context-grid">{status(true,copy.profile)}{status(Boolean(context.data?.assessment),copy.assessment)}{status(Boolean(context.data?.bodyAnalysis),copy.body,context.data?.analysisWeek)}{status(Boolean(context.data?.photos),copy.photos,context.data?.photos||null)}</div>{(!context.data?.assessment||!context.data?.bodyAnalysis)&&<Link href="/avaliacao" className="ai-outline-btn">{copy.complete}</Link>}</section>
  <section className="ai-confirm-card"><h2>{language==="pt"?"Confirme sua avaliação":language==="es"?"Confirma tu evaluación":"Confirm your assessment"}</h2>{context.data?.assessmentData?<div className="ai-assessment-summary"><span>Peso: <b>{context.data.assessmentData.weightKg||"—"} kg</b></span><span>Altura: <b>{context.data.assessmentData.heightCm} cm</b></span><span>{language==="pt"?"Sono":language==="es"?"Sueño":"Sleep"}: <b>{context.data.assessmentData.sleep}</b></span><span>{language==="pt"?"Recuperação":language==="es"?"Recuperación":"Recovery"}: <b>{context.data.assessmentData.recovery}</b></span><span>{language==="pt"?"Fotos":language==="es"?"Fotos":"Photos"}: <b>{context.data.photos}/4</b></span></div>:<p>{copy.missing}</p>}<div className="ai-confirm-actions"><button className={assessmentConfirmed?"confirmed":""} disabled={!context.data?.assessment} onClick={()=>setAssessmentConfirmed(true)}>{assessmentConfirmed?"✓ ":""}{language==="pt"?"Confirmar e continuar":language==="es"?"Confirmar y continuar":"Confirm and continue"}</button><Link href="/avaliacao">{language==="pt"?"Corrigir informações":language==="es"?"Corregir información":"Correct information"}</Link></div><p className="ai-attempts">{language==="pt"?"Tentativas disponíveis":language==="es"?"Intentos disponibles":"Attempts available"}: <b>{context.data?.unlimitedAttempts?"∞":`${context.data?.attemptsRemaining ?? 10}/${context.data?.attemptsLimit ?? 10}`}</b></p></section><div className="ai-mode-grid"><section className="ai-mode-card active"><Sparkles/><h2>{copy.full}</h2><p>{copy.fullDesc}</p></section></div>
  <section className="ai-chat-card"><h2>{copy.howMany}</h2><div className="ai-count-row">{[1,2,3,4,5,6,7].map(n=><button key={n} className={count===n?"active":""} onClick={()=>{if(!plans.length)setCount(n)}}>{n}</button>)}</div><p className="ai-chat-hint">{language==="pt"?"Qual é o seu objetivo?":language==="es"?"¿Cuál es tu objetivo?":"What is your goal?"}</p><div className="ai-goal-grid">{(user.experience==="woman"?[ ["Glúteos em destaque","Prioridade estética para glúteos"],["Pernas + Glúteos","Desenvolvimento combinado de inferiores"],["Inferiores desenvolvidos","Maior desenvolvimento dos membros inferiores"],["Shape feminino equilibrado e atlético","Equilíbrio corporal, estética e condicionamento"],["Definição","Composição corporal e preservação muscular"],["Performance e condicionamento","Desempenho e capacidade física"],["Força com foco em inferiores","Força com ênfase nos membros inferiores"] ]:[ ["Shape em V","Dorsais, ombros e proporção ombro/cintura"],["Shape Atlético","Físico equilibrado, força e condicionamento"],["Hipertrofia","Desenvolvimento muscular global"],["Definição","Composição corporal e preservação muscular"],["Força","Desenvolvimento de força"],["Performance","Desempenho e capacidade física"] ]).map(([name,desc])=><button type="button" key={name} className={`ai-goal-card ${goal===name?"active":""}`} onClick={()=>setGoal(name)}><b>{name}</b><small>{desc}</small></button>)}</div><div className="ai-messages">{messages.map((m,i)=><div key={i} className={`ai-message ${m.role}`}><b>{m.role==="ai"?"RITMO AI":(user.name||"Você")}</b><p>{m.text}</p></div>)}{generate.isPending&&<div className="ritmo-processing" role="status" aria-live="polite"><div className="ritmo-processing-mark"><Sparkles size={30}/><span/></div><b>{language==="pt"?"Criando seu programa":language==="es"?"Creando tu programa":"Building your program"}</b><div className="ritmo-processing-steps"><span>Analisando sua avaliação</span><span>Identificando prioridades</span><span>Montando seu programa</span><span>Validando exercícios e séries</span><span>Finalizando</span></div><small>{language==="pt"?"A estrutura é validada automaticamente antes de aparecer para você.":language==="es"?"La estructura se valida automáticamente antes de mostrarse.":"The structure is automatically validated before it is shown."}</small></div>}</div>
  <div className="ai-composer"><textarea rows={2} maxLength={1200} value={message} onChange={e=>setMessage(e.target.value)} placeholder={language==="pt"?"Preferência ou restrição adicional — opcional. Ex.: tenho 45 minutos ou não tenho determinada máquina.":language==="es"?"Preferencia o restricción adicional — opcional.":"Additional preference or restriction — optional."}/><button disabled={generate.isPending || !assessmentConfirmed || !goal || (!context.data?.unlimitedAttempts && context.data?.attemptsRemaining===0)} onClick={send}>{generate.isPending?<LoaderCircle className="animate-spin"/>:<Send/>}<span>{plans.length?copy.refine:copy.start}</span></button></div>{error&&<p className="ai-error">{error}</p>}</section>
  {plans.length>0&&<section className="ai-program-draft"><div className="ai-draft-head"><div><h2>{language==="pt"?"Treino criado pela IA":language==="es"?"Entrenamiento creado por IA":"Workout created by AI"}</h2><p>{copy.draft} · {language==="pt"?"Revise antes de confirmar. Gerar não aplica automaticamente.":language==="es"?"Revísalo antes de confirmar. Generar no lo aplica automáticamente.":"Review before confirming. Generating does not apply it automatically."}</p></div><button disabled={save.isPending} onClick={()=>save.mutate({plans})}>{save.isPending?copy.saving:(language==="pt"?"Confirmar treino":language==="es"?"Confirmar entrenamiento":"Confirm workout")}</button></div><div className="ai-plan-grid">{plans.map((plan,i)=><article key={i}><span>{language==="pt"?"TREINO":language==="es"?"ENTRENAMIENTO":"WORKOUT"} {i+1}</span><h3>{plan.name}</h3><p>{plan.focusGroup} · {plan.durationMinutes} min</p><ol>{plan.exercises.map((ex,j)=><li key={j}><b>{exerciseById[ex.exerciseId].name}</b><small>{ex.sets} × {ex.reps} · {ex.restSeconds}s</small></li>)}</ol></article>)}</div></section>}</div></main>;
}

export default function WorkoutBuilder() {
  const { user, loading } = useAuth();
  const [language] = useRitmoLanguage(); const [, setLocation] = useLocation();
  const query = trpc.workouts.list.useQuery(undefined, { enabled: !!user }); const utils = trpc.useUtils();
  const aiMode = new URLSearchParams(window.location.search).get("mode") === "ai";
  const defaultWorkoutTemplates = templatesFor(user?.experience ?? "man");
  const baseId = new URLSearchParams(window.location.search).get("base") as keyof typeof defaultWorkoutTemplates | null;
  const editId = Number(new URLSearchParams(window.location.search).get("edit")) || null;
  const [draft, setDraft] = useState<PlanDraft>(() => {
    if (baseId && defaultWorkoutTemplates[baseId]) { const template = defaultWorkoutTemplates[baseId]; return { ...template, exercises: originalSnapshot(baseId, user?.experience ?? "man").exercises.map(e => ({ ...e, note: e.note ?? null })), notes: "Uma cópia personalizada do treino sugerido. O treino original permanece intacto." }; }
    return emptyPlan;
  });
  useEffect(() => {
    if (user && baseId && !editId && defaultWorkoutTemplates[baseId]) {
      const template = defaultWorkoutTemplates[baseId];
      setDraft({ ...template, exercises: originalSnapshot(baseId, user.experience ?? "man").exercises.map(e => ({ ...e, note: e.note ?? null })), notes: "Uma cópia personalizada do treino sugerido. O treino original permanece intacto." });
    }
  }, [user?.experience, baseId, editId]);
  const preferences = trpc.fitness.overview.useQuery(undefined, { enabled: !!user });
  const [availabilityDays, setAvailabilityDays] = useState(4);
  useEffect(() => { if (preferences.data) setAvailabilityDays(preferences.data.preferences.workoutsPerWeek); }, [preferences.data?.preferences.workoutsPerWeek]); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const save = trpc.workouts.create.useMutation({ onSuccess: async () => { await utils.workouts.list.invalidate(); await utils.fitness.overview.invalidate(); setLocation("/treinos"); }, onError: err => setError(err.message) });
  const update = trpc.workouts.update.useMutation({ onSuccess: async () => { await utils.workouts.list.invalidate(); await utils.fitness.overview.invalidate(); setLocation("/treinos"); }, onError: err => setError(err.message) });
  const ai = trpc.workouts.generateWithAI.useMutation({ onSuccess: result => { setDraft({ ...result, notes: result.notes ?? null, exercises: result.exercises.map(item => ({ ...item, note: item.note ?? null })) }); setNotice("Rascunho pronto. Revise os exercícios e ajuste o plano antes de salvar."); setError(""); }, onError: err => setError(err.message) });
  useEffect(() => { if (!editId || !query.data) return; const plan = query.data.find(item => item.id === editId); if (plan) setDraft({ name: plan.name, objective: plan.objective, focusGroup: plan.focusGroup, durationMinutes: plan.durationMinutes, notes: plan.notes, exercises: plan.exercises.map(item => ({ ...item, note: item.note ?? null })) }); }, [editId, query.data]);
  const busy = ai.isPending || save.isPending || update.isPending;
  const pageTitle = language === "en" ? (aiMode ? "Create workout with AI" : editId ? "Edit my workout" : baseId ? "Customize suggested workout" : "Create my workout") : language === "es" ? (aiMode ? "Crear entrenamiento con IA" : editId ? "Editar mi entrenamiento" : baseId ? "Personalizar entrenamiento sugerido" : "Crear mi entrenamiento") : (aiMode ? "Criar treino com IA" : editId ? "Editar meu treino" : baseId ? "Personalizar treino sugerido" : "Criar meu treino");
  const saveWorkout = () => { setError(""); setNotice(""); const input = { ...draft, notes: draft.notes || null, exercises: draft.exercises }; if (editId) update.mutate({ ...input, id: editId }); else save.mutate({ ...input, source: ai.data ? "ai" : "manual", baseWorkoutId: baseId ?? null }); };
  if (loading) return <main className="grid min-h-screen place-items-center">{W(language,"loading")}</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-3xl border bg-white p-8 text-center"><h1 className="text-2xl font-bold">Entre para criar seus treinos</h1><Link href="/login" className="mt-4 inline-flex rounded-xl bg-emerald-950 px-5 py-3 font-semibold text-white">{W(language,"signin")}</Link></div></main>;
  if (user && !user.experience) return <Redirect to="/escolher-versao" />;
  if (aiMode) return <AIProgramBuilder user={user} language={language}/>;
  return <main className="min-h-screen bg-[#0b0d0c] workout-workspace px-4 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/treinos" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>{W(language,"myworkouts")}</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">{W(language,"custom")}</p><h1 className="mt-1 text-3xl font-semibold">{pageTitle}</h1><p className="mt-2 text-slate-600">Os quatro treinos sugeridos continuam preservados. Suas alterações são salvas como um plano próprio.</p>
    {aiMode && !editId && !baseId && <section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50/70 p-5"><div className="flex items-start gap-3"><Sparkles className="mt-1 shrink-0 text-emerald-900"/><div className="w-full"><h2 className="font-semibold">{W(language,"createAI")}</h2><p className="mt-1 text-sm text-slate-600">A recomendação considera sua avaliação, registros recentes, recuperação, cardio, dados de smartwatch disponíveis e análise corporal mais recente. A geração acontece somente quando você pedir. Um rascunho válido por semana; disponível novamente na segunda-feira (Europe/Lisbon).</p><div className="mt-4 grid gap-3 sm:grid-cols-4"><label className="text-xs font-semibold">{W(language,"goal")}<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={draft.objective} onChange={e => setDraft({ ...draft, objective: e.target.value })}/></label><label className="text-xs font-semibold">{W(language,"muscle")}<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={draft.focusGroup} onChange={e => setDraft({ ...draft, focusGroup: e.target.value })}/></label><label className="text-xs font-semibold">Duração (min)<input type="number" min={10} max={180} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={draft.durationMinutes} onChange={e => setDraft({ ...draft, durationMinutes: Number(e.target.value) })}/></label><label className="text-xs font-semibold">Dias disponíveis/semana<input type="number" min={1} max={7} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={availabilityDays} onChange={e => setAvailabilityDays(Number(e.target.value))}/></label></div><button disabled={busy} onClick={() => { setError(""); setNotice(""); ai.mutate({ objective: draft.objective, focusGroup: draft.focusGroup, durationMinutes: draft.durationMinutes, availabilityDays, language }); }} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{ai.isPending ? <LoaderCircle className="animate-spin" size={16}/> : <Sparkles size={16}/>} {ai.isPending ? "Analisando seus dados…" : "Criar com IA"}</button></div></div></section>}
    <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><div className="mb-6"><h2 className="font-semibold">{ai.data ? "Revise seu treino" : baseId ? "Edite sua cópia" : "Monte seu plano"}</h2><p className="mt-1 text-sm text-slate-500">Ajuste séries, repetições e a ordem dos movimentos.</p></div><PlanFields value={draft} onChange={setDraft}/>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}<div className="mt-7 flex flex-wrap justify-end gap-3"><Link href="/treinos" className="rounded-xl border px-4 py-3 text-sm font-semibold">{W(language,"cancel")}</Link><button disabled={busy || draft.exercises.length === 0} onClick={saveWorkout} className="rounded-xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? W(language,"saving") : editId ? W(language,"saveChanges") : W(language,"save")}</button></div></section>
  </div></main>;
}
