import { useEffect, useMemo, useState } from "react";
import { Link, Redirect, useLocation } from "wouter";
import { useAuth } from "@/_core/hooks/useAuth";
import { trpc } from "@/lib/trpc";
import { templatesFor, catalogFor, exerciseById, type ExerciseId } from "@shared/workouts";
import { originalSnapshot } from "@shared/fitness";
import { originalPrescriptions } from "@shared/original-prescriptions";
import { ArrowLeft, ArrowDown, ArrowUp, Dumbbell, LoaderCircle, Plus, Sparkles, Trash2 } from "lucide-react";

type ExerciseDraft = { exerciseId: ExerciseId; sets: number; reps: string; loadKg: number | null; restSeconds: number; note: string | null };
type PlanDraft = { name: string; objective: string; focusGroup: string; durationMinutes: number; notes: string | null; exercises: ExerciseDraft[] };
const emptyPlan: PlanDraft = { name: "Meu treino", objective: "Hipertrofia", focusGroup: "Corpo todo", durationMinutes: 45, notes: "", exercises: [] };
const freshExercise = (exerciseId: ExerciseId): ExerciseDraft => ({ exerciseId, sets: 3, reps: "8–12", loadKg: null, restSeconds: 90, note: null });
const pickerGroup = (exercise: (typeof exerciseById)[ExerciseId]) => {
  const name = exercise.name.toLowerCase();
  const group = exercise.group.toLowerCase();
  if (group.includes("peito")) return "Peito";
  if (group.includes("costa")) return "Costas";
  if (group.includes("ombro")) return "Ombros";
  if (group.includes("bíceps") || group.includes("biceps")) return "Bíceps";
  if (group.includes("tríceps") || group.includes("triceps")) return "Tríceps";
  if (group.includes("abd") || name.includes("prancha") || name.includes("core")) return "Abdómen / Core";
  if (group.includes("panturr")) return "Pernas · Panturrilhas";
  if (group.includes("glúte") || name.includes("pélvic") || name.includes("hip thrust") || name.includes("abdutora")) return "Pernas · Glúteos";
  if (name.includes("flexora") || name.includes("stiff")) return "Pernas · Posterior";
  return "Pernas · Quadríceps";
};
const pickerOrder = ["Peito", "Costas", "Ombros", "Bíceps", "Tríceps", "Abdómen / Core", "Pernas · Quadríceps", "Pernas · Posterior", "Pernas · Glúteos", "Pernas · Panturrilhas"];
const exerciseImage = (id: ExerciseId) => {
  const exercise = exerciseById[id] as (typeof exerciseById)[ExerciseId] & { image?: string };
  return exercise.image ?? originalPrescriptions[id]?.image ?? "";
};

function PlanFields({ value, onChange }: { value: PlanDraft; onChange: (next: PlanDraft) => void }) {
  const { user } = useAuth();
  const exerciseCatalog = catalogFor(user?.experience ?? "man");
  const [pickerOpen, setPickerOpen] = useState(false);
  const [search, setSearch] = useState("");
  const [selected, setSelected] = useState<ExerciseId[]>([]);
  const update = (key: keyof PlanDraft, next: unknown) => onChange({ ...value, [key]: next });
  const updateExercise = (index: number, patch: Partial<ExerciseDraft>) => onChange({ ...value, exercises: value.exercises.map((item, i) => i === index ? { ...item, ...patch } : item) });
  const moveExercise = (index: number, by: number) => { const exercises = [...value.exercises]; const next = index + by; if (next < 0 || next >= exercises.length) return; [exercises[index], exercises[next]] = [exercises[next], exercises[index]]; onChange({ ...value, exercises }); };
  const groups = useMemo(() => pickerOrder.filter(group => exerciseCatalog.some(e => pickerGroup(e as (typeof exerciseById)[ExerciseId]) === group)), [exerciseCatalog]);
  const addSelected = () => { const existing = new Set(value.exercises.map(e => e.exerciseId)); const additions = selected.filter(id => !existing.has(id)).map(freshExercise); onChange({ ...value, exercises: [...value.exercises, ...additions] }); setSelected([]); setSearch(""); setPickerOpen(false); };
  const toggle = (id: ExerciseId) => setSelected(current => current.includes(id) ? current.filter(x => x !== id) : [...current, id]);
  return <div className="space-y-6">
    <div className="grid gap-4 sm:grid-cols-2">
      <label className="text-sm font-medium">Nome do treino<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" maxLength={120} value={value.name} onChange={e => update("name", e.target.value)} /></label>
      <label className="text-sm font-medium">Objetivo<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" maxLength={80} value={value.objective} onChange={e => update("objective", e.target.value)} placeholder="Força, hipertrofia…" /></label>
      <label className="text-sm font-medium">Grupo muscular<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" maxLength={80} value={value.focusGroup} onChange={e => update("focusGroup", e.target.value)} /></label>
      <label className="text-sm font-medium">Duração estimada (min)<input className="mt-1.5 w-full rounded-xl border px-3 py-2.5" type="number" min={10} max={240} value={value.durationMinutes} onChange={e => update("durationMinutes", Number(e.target.value))} /></label>
    </div>
    <label className="block text-sm font-medium">Observações<textarea className="mt-1.5 w-full rounded-xl border px-3 py-2.5" rows={2} maxLength={2000} value={value.notes ?? ""} onChange={e => update("notes", e.target.value)} placeholder="Orientações para esta sessão" /></label>
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h3 className="font-semibold">Exercícios</h3><p className="text-sm text-slate-500">Escolha por grupo muscular e adicione vários de uma vez.</p></div><button type="button" disabled={value.exercises.length >= 20} onClick={() => setPickerOpen(true)} className="inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold disabled:opacity-50"><Plus size={16}/>Adicionar exercício</button></div>
    {pickerOpen && <div className="rounded-2xl border bg-white p-4 shadow-lg"><div className="flex items-center justify-between gap-3"><div><h3 className="font-semibold">Adicionar exercícios</h3><p className="text-xs text-slate-500">Selecione por grupo muscular.</p></div><button type="button" className="rounded-lg border px-3 py-2 text-sm" onClick={() => {setPickerOpen(false);setSelected([]);setSearch("");}}>Fechar</button></div><input autoFocus className="mt-4 w-full rounded-xl border px-3 py-2.5" placeholder="Pesquisar exercício…" value={search} onChange={e=>setSearch(e.target.value)}/><div className="mt-4 max-h-[55vh] space-y-4 overflow-y-auto pr-1">{groups.map(group => { const items=exerciseCatalog.filter(e=>pickerGroup(e as (typeof exerciseById)[ExerciseId])===group && (!search || e.name.toLowerCase().includes(search.toLowerCase()))); if(!items.length)return null; return <section key={group}><h4 className="sticky top-0 z-10 bg-white py-2 text-sm font-bold uppercase tracking-wide">{group}</h4><div className="grid gap-2 sm:grid-cols-2">{items.map(exercise=>{const id=exercise.id as ExerciseId;const already=value.exercises.some(x=>x.exerciseId===id);const checked=selected.includes(id);const image=exerciseImage(id);return <button type="button" key={id} disabled={already} onClick={()=>toggle(id)} className={`flex items-center gap-3 rounded-xl border p-3 text-left ${checked?'border-emerald-700 bg-emerald-50':''} disabled:opacity-60`}>{image && <img src={image} alt="" className="h-16 w-16 shrink-0 rounded-lg border bg-slate-100 object-cover" loading="lazy"/>}<span className="min-w-0 flex-1"><strong className="block text-sm">{exercise.name}</strong><small className="text-slate-500">{already?'Já adicionado':group}</small></span><span className="grid h-7 w-7 shrink-0 place-items-center rounded-full border font-bold">{already?'✓':checked?'✓':''}</span></button>})}</div></section>})}</div><button type="button" disabled={!selected.length || value.exercises.length + selected.length > 20} onClick={addSelected} className="mt-4 w-full rounded-xl bg-emerald-950 px-4 py-3 font-semibold text-white disabled:opacity-50">{selected.length ? `Adicionar ${selected.length} exercício${selected.length>1?'s':''}` : 'Selecione exercícios'}</button></div>}
    {!value.exercises.length && <div className="rounded-2xl border border-dashed p-7 text-center text-sm text-slate-500">Adicione o primeiro exercício para montar seu treino.</div>}
    <div className="space-y-3">{value.exercises.map((item,index)=><article key={`${index}-${item.exerciseId}`} className="rounded-2xl border border-slate-200 bg-slate-50/70 p-4"><div className="mb-3 flex items-center gap-2"><span className="grid h-7 w-7 place-items-center rounded-full bg-emerald-950 text-xs font-bold text-white">{index+1}</span><strong className="min-w-0 flex-1 text-sm">{exerciseById[item.exerciseId].name} <span className="font-normal text-slate-500">· {exerciseById[item.exerciseId].group}</span></strong><button type="button" aria-label="Mover para cima" disabled={index===0} className="rounded-lg p-2 disabled:opacity-30" onClick={()=>moveExercise(index,-1)}><ArrowUp size={16}/></button><button type="button" aria-label="Mover para baixo" disabled={index===value.exercises.length-1} className="rounded-lg p-2 disabled:opacity-30" onClick={()=>moveExercise(index,1)}><ArrowDown size={16}/></button><button type="button" aria-label="Remover exercício" className="rounded-lg p-2 text-red-700" onClick={()=>onChange({...value,exercises:value.exercises.filter((_,i)=>i!==index)})}><Trash2 size={16}/></button></div><div className="grid grid-cols-2 gap-3 sm:grid-cols-4"><label className="text-xs font-semibold text-slate-600">Séries<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" type="number" min={1} max={10} value={item.sets} onChange={e=>updateExercise(index,{sets:Number(e.target.value)})}/></label><label className="text-xs font-semibold text-slate-600">Repetições<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" maxLength={24} value={item.reps} onChange={e=>updateExercise(index,{reps:e.target.value})}/></label><label className="text-xs font-semibold text-slate-600">Carga (kg)<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" type="number" min={0} max={500} step="0.5" value={item.loadKg??""} onChange={e=>updateExercise(index,{loadKg:e.target.value===""?null:Number(e.target.value)})}/></label><label className="text-xs font-semibold text-slate-600">Descanso (seg.)<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" type="number" min={0} max={900} step={15} value={item.restSeconds} onChange={e=>updateExercise(index,{restSeconds:Number(e.target.value)})}/></label></div><label className="mt-3 block text-xs font-semibold text-slate-600">Nota<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" maxLength={240} value={item.note??""} onChange={e=>updateExercise(index,{note:e.target.value||null})}/></label></article>)}</div>
  </div>;
}
export function WorkoutsLibrary() {
  const { user, loading } = useAuth(); const [, setLocation] = useLocation();
  const defaultWorkoutTemplates = templatesFor(user?.experience ?? "man");
  const query = trpc.workouts.list.useQuery(undefined, { enabled: !!user });
  const overview = trpc.fitness.overview.useQuery(undefined, { enabled: !!user });
  const utils = trpc.useUtils();
  const preferences = trpc.fitness.preferences.useMutation({ onSuccess: () => overview.refetch() });
  const copy = trpc.workouts.create.useMutation({ onSuccess: () => Promise.all([utils.workouts.list.invalidate(), utils.fitness.overview.invalidate()]) });
  const remove = trpc.workouts.remove.useMutation({ onSuccess: () => Promise.all([utils.workouts.list.invalidate(), utils.fitness.overview.invalidate()]) });
  if (loading) return <main className="grid min-h-screen place-items-center">Carregando sua conta…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="max-w-md rounded-3xl border bg-white p-8 text-center"><Dumbbell className="mx-auto text-emerald-900"/><h1 className="mt-4 text-2xl font-bold">Entre para ver seus treinos</h1><p className="my-3 text-slate-600">Seus planos ficam salvos com segurança na sua conta.</p><Link href="/login" className="inline-flex rounded-xl bg-emerald-950 px-5 py-3 font-semibold text-white">Entrar</Link></div></main>;
  if (user && !user.experience) return <Redirect to="/escolher-versao" />;
  return <main className="min-h-screen bg-[#0b0d0c] workout-workspace px-4 py-8 sm:px-8"><div className="mx-auto max-w-6xl"><header className="flex flex-wrap items-center justify-between gap-4"><div><Link href="/treino" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>Voltar ao treino</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">Sua biblioteca</p><h1 className="mt-1 text-3xl font-semibold">Treinos salvos</h1><p className="mt-2 text-slate-600">Planos criados por você e personalizados a partir dos quatro treinos sugeridos.</p></div></header>
    <section className="mt-8"><div className="mb-5 rounded-2xl border bg-white p-5"><label className="text-sm font-semibold">Treinos por semana<select className="ml-3 rounded-lg border px-3 py-2" aria-label="Treinos por semana" value={overview.data?.preferences.workoutsPerWeek ?? 4} disabled={!overview.data || preferences.isPending} onChange={e => overview.data && preferences.mutate({ ...overview.data.preferences, workoutsPerWeek: Number(e.target.value) })}>{[1,2,3,4,5,6,7].map(n => <option key={n} value={n}>{n}</option>)}</select></label><p className="mt-2 text-sm text-slate-500">Escolha entre 1 e 7 treinos por semana. Os quatro treinos sugeridos permanecem como base.</p>{preferences.error && <p role="alert" className="mt-2 text-sm text-red-700">{preferences.error.message}</p>}</div><div className="mb-4"><h2 className="text-xl font-semibold">Quatro treinos sugeridos</h2><p className="mt-1 text-sm text-slate-500">A estrutura original é mantida. Personalize criando uma cópia para sua conta.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{Object.entries(defaultWorkoutTemplates).map(([day, plan], index) => <article key={day} className="rounded-2xl border bg-white p-5"><span className="text-xs font-bold uppercase tracking-wider text-emerald-800">TREINO SUGERIDO {index + 1}</span><h3 className="mt-2 font-semibold">{plan.name}</h3><p className="mt-1 text-sm text-slate-500">{plan.focusGroup} · {plan.exercises.length} exercícios</p><Link href={"/treinos/criar?base=" + day} className="mt-4 inline-flex rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">Personalizar cópia</Link></article>)}{[{ label: "Criar treino com IA", href: "/treinos/criar?mode=ai", icon: Sparkles }, { label: "Acrescentar mais treinos", href: "/treinos/criar", icon: Dumbbell }].map(action => { const Icon = action.icon; return <article key={action.href} className="rounded-2xl border bg-white p-5"><Icon className="text-emerald-800"/><h3 className="mt-2 font-semibold">{action.label}</h3><Link href={action.href} className="mt-4 inline-flex rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">{action.label}</Link></article>; })}</div></section>
    <div className="mb-4 mt-10"><h2 className="text-xl font-semibold">Meus planos</h2><p className="mt-1 text-sm text-slate-500">Treinos privados criados e personalizados por você.</p></div>
    {(copy.error || remove.error) && <p role="alert">{copy.error?.message || remove.error?.message}</p>}<div className="mt-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-3">{query.isLoading && <p>Carregando seus treinos…</p>}{query.error && <p role="alert" className="text-red-700">Não foi possível carregar os treinos.</p>}{!query.isLoading && query.data?.length === 0 && <div className="rounded-2xl border border-dashed bg-white p-8 text-slate-600">Você ainda não salvou treinos. Crie um plano manual ou peça uma sugestão personalizada à IA.</div>}{query.data?.map(plan => <article key={plan.id} className="group rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-3"><div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-bold text-emerald-900">{plan.source === "ai" ? "CRIADO COM IA" : plan.source === "customized" ? "PERSONALIZADO" : plan.source === "day5" ? "DIA 5 OPCIONAL" : "MEU TREINO"}</span><h2 className="mt-3 text-lg font-semibold">{plan.name}</h2></div><Dumbbell className="shrink-0 text-emerald-900" size={20}/></div><p className="mt-1 text-sm text-slate-500">{plan.focusGroup} · {plan.durationMinutes} min</p><p className="mt-3 text-sm text-slate-700">{plan.exercises.length} exercícios · {plan.objective}</p><div className="mt-4 flex flex-wrap gap-2"><Link href={`/treino?plan=${plan.id}`} className="rounded-lg border px-3 py-2 text-sm font-semibold">Executar</Link><button disabled={copy.isPending} onClick={() => copy.mutate({name: (plan.name + " — cópia").slice(0,120),objective:plan.objective,focusGroup:plan.focusGroup,durationMinutes:plan.durationMinutes,notes:plan.notes,exercises:plan.exercises,source:"manual",baseWorkoutId:null})} className="rounded-lg border px-3 py-2 text-sm font-semibold">Copiar</button><button onClick={() => setLocation(`/treinos/criar?edit=${plan.id}`)} className="flex-1 rounded-lg border px-3 py-2 text-sm font-semibold hover:bg-slate-50">Editar</button><button disabled={remove.isPending} onClick={() => { if (window.confirm(`Excluir “${plan.name}”?`)) remove.mutate({ id: plan.id }); }} className="sm:opacity-0 group-hover:opacity-100 focus:opacity-100 rounded-lg border border-red-200 px-3 py-2 text-sm font-semibold text-red-700 hover:bg-red-50">Excluir treino</button></div></article>)}</div>
  </div></main>;
}

export default function WorkoutBuilder() {
  const { user, loading } = useAuth(); const [, setLocation] = useLocation();
  const query = trpc.workouts.list.useQuery(undefined, { enabled: !!user }); const utils = trpc.useUtils();
  const aiMode = new URLSearchParams(window.location.search).get("mode") === "ai";
  const defaultWorkoutTemplates = templatesFor(user?.experience ?? "man");
  const baseId = new URLSearchParams(window.location.search).get("base") as keyof typeof defaultWorkoutTemplates | null;
  const editId = Number(new URLSearchParams(window.location.search).get("edit")) || null;
  const [draft, setDraft] = useState<PlanDraft>(() => {
    if (baseId && defaultWorkoutTemplates[baseId]) { const template = defaultWorkoutTemplates[baseId]; return { ...template, exercises: originalSnapshot(baseId, user?.experience ?? "man").exercises.map(e => ({ ...e, note: e.note ?? null })), notes: "Uma cópia personalizada do treino sugerido. O treino original permanece intacto." }; }
    return emptyPlan;
  });
  useEffect(() => {
    if (user && baseId && !editId && defaultWorkoutTemplates[baseId]) {
      const template = defaultWorkoutTemplates[baseId];
      setDraft({ ...template, exercises: originalSnapshot(baseId, user.experience ?? "man").exercises.map(e => ({ ...e, note: e.note ?? null })), notes: "Uma cópia personalizada do treino sugerido. O treino original permanece intacto." });
    }
  }, [user?.experience, baseId, editId]);
  const preferences = trpc.fitness.overview.useQuery(undefined, { enabled: !!user });
  const [availabilityDays, setAvailabilityDays] = useState(4);
  useEffect(() => { if (preferences.data) setAvailabilityDays(preferences.data.preferences.workoutsPerWeek); }, [preferences.data?.preferences.workoutsPerWeek]); const [notice, setNotice] = useState(""); const [error, setError] = useState("");
  const save = trpc.workouts.create.useMutation({ onSuccess: async () => { await utils.workouts.list.invalidate(); await utils.fitness.overview.invalidate(); setLocation("/treinos"); }, onError: err => setError(err.message) });
  const update = trpc.workouts.update.useMutation({ onSuccess: async () => { await utils.workouts.list.invalidate(); await utils.fitness.overview.invalidate(); setLocation("/treinos"); }, onError: err => setError(err.message) });
  const ai = trpc.workouts.generateWithAI.useMutation({ onSuccess: result => { setDraft({ ...result, notes: result.notes ?? null, exercises: result.exercises.map(item => ({ ...item, note: item.note ?? null })) }); setNotice("Rascunho pronto. Revise os exercícios e ajuste o plano antes de salvar."); setError(""); }, onError: err => setError(err.message) });
  useEffect(() => { if (!editId || !query.data) return; const plan = query.data.find(item => item.id === editId); if (plan) setDraft({ name: plan.name, objective: plan.objective, focusGroup: plan.focusGroup, durationMinutes: plan.durationMinutes, notes: plan.notes, exercises: plan.exercises.map(item => ({ ...item, note: item.note ?? null })) }); }, [editId, query.data]);
  const busy = ai.isPending || save.isPending || update.isPending;
  const pageTitle = aiMode ? "Criar treino com IA" : editId ? "Editar meu treino" : baseId ? "Personalizar treino sugerido" : "Criar meu treino";
  const saveWorkout = () => { setError(""); setNotice(""); const input = { ...draft, notes: draft.notes || null, exercises: draft.exercises }; if (editId) update.mutate({ ...input, id: editId }); else save.mutate({ ...input, source: ai.data ? "ai" : "manual", baseWorkoutId: baseId ?? null }); };
  if (loading) return <main className="grid min-h-screen place-items-center">Carregando sua conta…</main>;
  if (!user) return <main className="grid min-h-screen place-items-center p-6"><div className="rounded-3xl border bg-white p-8 text-center"><h1 className="text-2xl font-bold">Entre para criar seus treinos</h1><Link href="/login" className="mt-4 inline-flex rounded-xl bg-emerald-950 px-5 py-3 font-semibold text-white">Entrar</Link></div></main>;
  if (user && !user.experience) return <Redirect to="/escolher-versao" />;
  return <main className="min-h-screen bg-[#0b0d0c] workout-workspace px-4 py-8 sm:px-8"><div className="mx-auto max-w-4xl"><Link href="/treinos" className="inline-flex items-center gap-2 text-sm font-semibold text-emerald-900"><ArrowLeft size={16}/>Meus treinos</Link><p className="mt-5 text-xs font-bold uppercase tracking-[.18em] text-emerald-800">Treinamento personalizado</p><h1 className="mt-1 text-3xl font-semibold">{pageTitle}</h1><p className="mt-2 text-slate-600">Os quatro treinos sugeridos continuam preservados. Suas alterações são salvas como um plano próprio.</p>
    {aiMode && !editId && !baseId && <section className="mt-6 rounded-2xl border border-emerald-200 bg-emerald-50/70 p-5"><div className="flex items-start gap-3"><Sparkles className="mt-1 shrink-0 text-emerald-900"/><div className="w-full"><h2 className="font-semibold">Criar com IA</h2><p className="mt-1 text-sm text-slate-600">A recomendação considera sua avaliação, registros recentes, recuperação, cardio, dados de smartwatch disponíveis e análise corporal mais recente. A geração acontece somente quando você pedir. Um rascunho válido por semana; disponível novamente na segunda-feira (Europe/Lisbon).</p><div className="mt-4 grid gap-3 sm:grid-cols-4"><label className="text-xs font-semibold">Objetivo<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={draft.objective} onChange={e => setDraft({ ...draft, objective: e.target.value })}/></label><label className="text-xs font-semibold">Grupo muscular<input className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={draft.focusGroup} onChange={e => setDraft({ ...draft, focusGroup: e.target.value })}/></label><label className="text-xs font-semibold">Duração (min)<input type="number" min={10} max={180} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={draft.durationMinutes} onChange={e => setDraft({ ...draft, durationMinutes: Number(e.target.value) })}/></label><label className="text-xs font-semibold">Dias disponíveis/semana<input type="number" min={1} max={7} className="mt-1 w-full rounded-lg border bg-white px-3 py-2 text-sm" value={availabilityDays} onChange={e => setAvailabilityDays(Number(e.target.value))}/></label></div><button disabled={busy} onClick={() => { setError(""); setNotice(""); ai.mutate({ objective: draft.objective, focusGroup: draft.focusGroup, durationMinutes: draft.durationMinutes, availabilityDays, language: "pt" }); }} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-emerald-950 px-4 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{ai.isPending ? <LoaderCircle className="animate-spin" size={16}/> : <Sparkles size={16}/>} {ai.isPending ? "Analisando seus dados…" : "Criar com IA"}</button></div></div></section>}
    <section className="mt-6 rounded-2xl border bg-white p-5 shadow-sm sm:p-7"><div className="mb-6"><h2 className="font-semibold">{ai.data ? "Revise seu treino" : baseId ? "Edite sua cópia" : "Monte seu plano"}</h2><p className="mt-1 text-sm text-slate-500">Ajuste séries, repetições, carga, descanso e ordem dos movimentos.</p></div><PlanFields value={draft} onChange={setDraft}/>{error && <p role="alert" className="mt-5 rounded-xl bg-red-50 p-3 text-sm text-red-800">{error}</p>}{notice && <p role="status" className="mt-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-900">{notice}</p>}<div className="mt-7 flex flex-wrap justify-end gap-3"><Link href="/treinos" className="rounded-xl border px-4 py-3 text-sm font-semibold">Cancelar</Link><button disabled={busy || draft.exercises.length === 0} onClick={saveWorkout} className="rounded-xl bg-emerald-950 px-5 py-3 text-sm font-semibold text-white disabled:opacity-50">{busy ? "Salvando…" : editId ? "Salvar alterações" : "Salvar treino"}</button></div></section>
  </div></main>;
}
