export type Language = "pt" | "en" | "es";
const pt = {
  retract: "Desmarcar série",
  dashboard: "Dashboard",
  training: "Treino",
  wellness: "Alimentação, água e cardio",
  body: "Corpo e progresso",
  history: "Histórico",
  profile: "Perfil",
  library: "Biblioteca de treinos",
  smartwatch: "Smartwatch",
  next: "Próximo recomendado",
  suggested: "TREINO SUGERIDO",
  sequenceHelp:
    "Quatro treinos em sequência recomendada. Você pode escolher qualquer um no dia atual; sugerido é recomendação, não obrigação.",
  calendar: "Data real",
  todayOnly: "Treinos só podem ser registrados hoje, no fuso Europe/Lisbon.",
  historyReadOnly:
    "Consulta de histórico. Registro de treinos disponível apenas hoje.",
  choose: "Escolha seu treino",
  start: "Iniciar treino",
  finished: "Finalizado",
  inProgress: "Em execução",
  confirmedSets: "séries confirmadas",
  partialHelp:
    "Somente séries confirmadas contam. Você pode finalizar uma sessão parcial.",
  noTraining: "Sem treino registrado nesta data.",
  rest: "Descanso",
  load: "Carga (kg)",
  unknown: "Não informado",
  startToRecord: "Inicie o treino para registrar séries realizadas.",
  set: "Série",
  seconds: "Segundos",
  actualReps: "Repetições realizadas",
  note: "Observações",
  correct: "Corrigir",
  confirmSet: "Confirmar série",
  sessionNote: "Observações da sessão",
  finish: "Confirmar e finalizar treino",
  photo: "Fotografia privada (opcional)",
  photoLimit: "Use uma imagem até 1,5 MB.",
  loading: "Carregando…",
  privatePhoto: "Fotografia privada do registro",
  photoUnavailable: "Fotografia indisponível",
  water: "Água",
  goal: "Meta diária (ml)",
  saveGoal: "Salvar meta",
  type: "Tipo de registro",
  amountMl: "Quantidade (ml; 0 para corrigir um registro indevido)",
  meals: "Alimentação",
  cardio: "Cardio",
  meal: "Refeição",
  food: "Alimentos informados",
  quantity: "Quantidade / porção informada",
  time: "Horário",
  modality: "Modalidade",
  duration: "Duração (min)",
  distance: "Distância conhecida (km)",
  intensity: "Intensidade informada",
  unspecified: "Não informada",
  light: "Leve",
  moderate: "Moderada",
  vigorous: "Vigorosa",
  manualCardioHelp:
    "Origem manual. Calorias ficam ausentes sem uma fonte válida. Registre apenas atividades que não estejam importadas do smartwatch.",
  save: "Salvar registro",
  cancel: "Cancelar correção",
  empty: "Sem registros. Adicione seus dados para acompanhar a evolução.",
  manual: "Manual",
  importedCardio: "Atividades importadas",
  noDoubleCounting:
    "Registros manuais e importados são mostrados separadamente; não são somados para evitar duplicação.",
  nutritionAI: "Análise alimentar sob solicitação",
  authorize:
    "Autorizo o envio de um resumo dos meus dados ao Gemini nesta solicitação.",
  analyze: "Solicitar análise",
  nutritionQuestion:
    "Analise meus registros alimentares da data indicada, distinguindo fatos informados e estimativas e indicando dados ausentes.",
  aiEstimate: "ESTIMATIVA POR IA",
  bodyHelp:
    "Informe medidas reais. O percentual de gordura informado não é calculado pelas fotos.",
  heightCm: "Altura (cm)",
  weightKg: "Peso (kg)",
  bodyFatPercent: "Gordura corporal informada (%)",
  waistCm: "Cintura (cm)",
  chestCm: "Peito (cm)",
  hipCm: "Quadril (cm)",
  progress: "Progresso",
  needTwoMeasurements:
    "Registre pelo menos dois pesos para comparar a evolução.",
  notClinical: "Não é medição clínica.",
  photoAnalysis: "Análise corporal por fotos",
  weekly: "Avaliação semanal",
  coachHelp:
    "Gemini 3.5 Flash Lite. Usa resumos do seu histórico somente com sua autorização; não diagnostica doenças.",
  question: "Sua pergunta",
  ask: "Perguntar ao AI Coach",
  finishedSessions: "sessões finalizadas",
  trainingDays: "dos dias no período de 90 dias",
  metricsHelp:
    "Volume = carga × repetições das séries confirmadas com ambos os valores. Volume parcial não representa o total de trabalho; segundos são exibidos separadamente.",
  volume: "Volume conhecido",
  reps: "Repetições",
  exerciseProgress: "Evolução por exercício",
  frequency: "datas com séries confirmadas",
  complete: "completo",
  partial: "parcial",
  legacy: "Histórico anterior preservado",
  legacyHelp:
    "Registros antigos são resumos de exercícios e não incluem séries/cargas. Não foram convertidos em séries realizadas.",
  exercises: "exercícios",
  todayTraining: "Treino de hoje",
  manualRecords: "registros manuais",
  importedRecords: "atividades importadas",
  disconnected: "DESCONECTADO",
  connect: "Gerenciar conexões",
  signInHelp: "Entre para acessar e salvar seus dados privados.",
  signIn: "Entrar",
  retry: "Tentar novamente",
  addRecord: "Adicionar registro",
};
type Copy = { [K in keyof typeof pt]: string };
const en: Copy = {
  retract: "Unconfirm set",
  dashboard: "Dashboard",
  training: "Training",
  wellness: "Food, water and cardio",
  body: "Body and progress",
  history: "History",
  profile: "Profile",
  library: "Workout library",
  smartwatch: "Smartwatch",
  next: "Next recommended",
  suggested: "SUGGESTED WORKOUT",
  sequenceHelp:
    "Four workouts in a recommended sequence. Choose any workout today; a suggestion is optional.",
  calendar: "Actual date",
  todayOnly: "Workouts can only be recorded today in Europe/Lisbon.",
  historyReadOnly: "Read-only history. Workouts can only be recorded today.",
  choose: "Choose your workout",
  start: "Start workout",
  finished: "Completed",
  inProgress: "In progress",
  confirmedSets: "confirmed sets",
  partialHelp: "Only confirmed sets count. You can finish a partial session.",
  noTraining: "No workout recorded for this date.",
  rest: "Rest",
  load: "Load (kg)",
  unknown: "Not provided",
  startToRecord: "Start the workout to record completed sets.",
  set: "Set",
  seconds: "Seconds",
  actualReps: "Actual repetitions",
  note: "Notes",
  correct: "Correct",
  confirmSet: "Confirm set",
  sessionNote: "Session notes",
  finish: "Confirm and finish workout",
  photo: "Private photo (optional)",
  photoLimit: "Use an image up to 1.5 MB.",
  loading: "Loading…",
  privatePhoto: "Private record photo",
  photoUnavailable: "Photo unavailable",
  water: "Water",
  goal: "Daily target (ml)",
  saveGoal: "Save target",
  type: "Record type",
  amountMl: "Amount (ml; 0 to correct an invalid record)",
  meals: "Food",
  cardio: "Cardio",
  meal: "Meal",
  food: "Reported foods",
  quantity: "Reported quantity / portion",
  time: "Time",
  modality: "Activity type",
  duration: "Duration (min)",
  distance: "Known distance (km)",
  intensity: "Reported intensity",
  unspecified: "Not provided",
  light: "Light",
  moderate: "Moderate",
  vigorous: "Vigorous",
  manualCardioHelp:
    "Manual source. Calories stay unknown without a valid source. Only record activities that have not been imported from your smartwatch.",
  save: "Save record",
  cancel: "Cancel correction",
  empty: "No records yet. Add your data to track progress.",
  manual: "Manual",
  importedCardio: "Imported activities",
  noDoubleCounting:
    "Manual and imported records are shown separately and are not added together to avoid duplication.",
  nutritionAI: "Food analysis on request",
  authorize:
    "I authorize sending a summary of my data to Gemini for this request.",
  analyze: "Request analysis",
  nutritionQuestion:
    "Analyze my food records for the indicated date, separating reported facts from estimates and stating missing data.",
  aiEstimate: "AI ESTIMATE",
  bodyHelp:
    "Enter actual measurements. Reported body fat is not calculated from photos.",
  heightCm: "Height (cm)",
  weightKg: "Weight (kg)",
  bodyFatPercent: "Reported body fat (%)",
  waistCm: "Waist (cm)",
  chestCm: "Chest (cm)",
  hipCm: "Hip (cm)",
  progress: "Progress",
  needTwoMeasurements: "Record at least two weights to compare progress.",
  notClinical: "Not a clinical measurement.",
  photoAnalysis: "Body photo analysis",
  weekly: "Weekly assessment",
  coachHelp:
    "Gemini 3.5 Flash Lite. Uses summaries of your history only with your authorization; does not diagnose disease.",
  question: "Your question",
  ask: "Ask AI Coach",
  finishedSessions: "completed sessions",
  trainingDays: "of days in the 90-day period",
  metricsHelp:
    "Volume = load × repetitions for confirmed sets with both values. Partial volume is not total work; timed sets are displayed separately.",
  volume: "Known volume",
  reps: "Repetitions",
  exerciseProgress: "Progress by exercise",
  frequency: "dates with confirmed sets",
  complete: "complete",
  partial: "partial",
  legacy: "Preserved previous history",
  legacyHelp:
    "Older records are exercise summaries without sets or loads. They have not been converted into completed sets.",
  exercises: "exercises",
  todayTraining: "Today's workout",
  manualRecords: "manual records",
  importedRecords: "imported activities",
  disconnected: "DISCONNECTED",
  connect: "Manage connections",
  signInHelp: "Sign in to access and save your private data.",
  signIn: "Sign in",
  retry: "Try again",
  addRecord: "Add record",
};
const es: Copy = {
  retract: "Desmarcar serie",
  dashboard: "Panel",
  training: "Entrenamiento",
  wellness: "Alimentación, agua y cardio",
  body: "Cuerpo y progreso",
  history: "Historial",
  profile: "Perfil",
  library: "Biblioteca de entrenamientos",
  smartwatch: "Smartwatch",
  next: "Próximo recomendado",
  suggested: "ENTRENAMIENTO SUGERIDO",
  sequenceHelp:
    "Cuatro entrenamientos en secuencia recomendada. Puedes elegir cualquiera hoy; la sugerencia es opcional.",
  calendar: "Fecha real",
  todayOnly: "Solo puedes registrar entrenamientos hoy, en Europe/Lisbon.",
  historyReadOnly:
    "Consulta del historial. Solo puedes registrar entrenamientos hoy.",
  choose: "Elige tu entrenamiento",
  start: "Iniciar entrenamiento",
  finished: "Finalizado",
  inProgress: "En ejecución",
  confirmedSets: "series confirmadas",
  partialHelp:
    "Solo cuentan las series confirmadas. Puedes finalizar una sesión parcial.",
  noTraining: "Sin entrenamiento registrado en esta fecha.",
  rest: "Descanso",
  load: "Carga (kg)",
  unknown: "No informado",
  startToRecord: "Inicia el entrenamiento para registrar series realizadas.",
  set: "Serie",
  seconds: "Segundos",
  actualReps: "Repeticiones realizadas",
  note: "Observaciones",
  correct: "Corregir",
  confirmSet: "Confirmar serie",
  sessionNote: "Observaciones de la sesión",
  finish: "Confirmar y finalizar entrenamiento",
  photo: "Fotografía privada (opcional)",
  photoLimit: "Usa una imagen de hasta 1,5 MB.",
  loading: "Cargando…",
  privatePhoto: "Fotografía privada del registro",
  photoUnavailable: "Fotografía no disponible",
  water: "Agua",
  goal: "Meta diaria (ml)",
  saveGoal: "Guardar meta",
  type: "Tipo de registro",
  amountMl: "Cantidad (ml; 0 para corregir un registro erróneo)",
  meals: "Alimentación",
  cardio: "Cardio",
  meal: "Comida",
  food: "Alimentos informados",
  quantity: "Cantidad / porción informada",
  time: "Horario",
  modality: "Modalidad",
  duration: "Duración (min)",
  distance: "Distancia conocida (km)",
  intensity: "Intensidad informada",
  unspecified: "No informada",
  light: "Leve",
  moderate: "Moderada",
  vigorous: "Vigorosa",
  manualCardioHelp:
    "Origen manual. Las calorías quedan ausentes sin fuente válida. Registra solo actividades que no se hayan importado del smartwatch.",
  save: "Guardar registro",
  cancel: "Cancelar corrección",
  empty: "Sin registros. Añade tus datos para seguir tu evolución.",
  manual: "Manual",
  importedCardio: "Actividades importadas",
  noDoubleCounting:
    "Los registros manuales e importados se muestran por separado y no se suman para evitar duplicados.",
  nutritionAI: "Análisis alimentario bajo solicitud",
  authorize:
    "Autorizo enviar un resumen de mis datos a Gemini para esta solicitud.",
  analyze: "Solicitar análisis",
  nutritionQuestion:
    "Analiza mis registros alimentarios de la fecha indicada, separando hechos informados de estimaciones e indicando datos ausentes.",
  aiEstimate: "ESTIMACIÓN POR IA",
  bodyHelp:
    "Introduce medidas reales. La grasa corporal informada no se calcula con las fotos.",
  heightCm: "Altura (cm)",
  weightKg: "Peso (kg)",
  bodyFatPercent: "Grasa corporal informada (%)",
  waistCm: "Cintura (cm)",
  chestCm: "Pecho (cm)",
  hipCm: "Cadera (cm)",
  progress: "Progreso",
  needTwoMeasurements:
    "Registra al menos dos pesos para comparar la evolución.",
  notClinical: "No es una medición clínica.",
  photoAnalysis: "Análisis corporal con fotos",
  weekly: "Evaluación semanal",
  coachHelp:
    "Gemini 3.5 Flash Lite. Usa resúmenes de tu historial solo con tu autorización; no diagnostica enfermedades.",
  question: "Tu pregunta",
  ask: "Preguntar al AI Coach",
  finishedSessions: "sesiones finalizadas",
  trainingDays: "de días en el período de 90 días",
  metricsHelp:
    "Volumen = carga × repeticiones de series confirmadas con ambos valores. El volumen parcial no representa el trabajo total; los segundos se muestran por separado.",
  volume: "Volumen conocido",
  reps: "Repeticiones",
  exerciseProgress: "Evolución por ejercicio",
  frequency: "fechas con series confirmadas",
  complete: "completo",
  partial: "parcial",
  legacy: "Historial anterior preservado",
  legacyHelp:
    "Los registros antiguos son resúmenes sin series ni cargas. No se han convertido en series realizadas.",
  exercises: "ejercicios",
  todayTraining: "Entrenamiento de hoy",
  manualRecords: "registros manuales",
  importedRecords: "actividades importadas",
  disconnected: "DESCONECTADO",
  connect: "Gestionar conexiones",
  signInHelp: "Inicia sesión para acceder y guardar tus datos privados.",
  signIn: "Iniciar sesión",
  retry: "Reintentar",
  addRecord: "Añadir registro",
};
export const fitnessCopy: Record<Language, Copy> = { pt, en, es };
